### ISSUE TITLE
Duplicate SLO created for each `DatadogSLO`

### ISSUE THREAD

**Issue by jeff-jsq** [DataDog/datadog-operator#1062]
**Describe what happened:**
I've confirmed I'm only running a single Datadog operator in my K8s cluster, but it seems each `DatadogSLO` creates multiple SLOs in Datadog.

Running `1.3.0` of the operator, creating an example `DatadogSLO`:

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogSLO
metadata:
  name: text-xyz
  namespace: test
spec:
  description: Error SLO for test-xyz
  name: Error SLO for test-xyz
  query:
    denominator: sum:trace.pyramid.request.hits{service:test-xyz, env:test}.as_count()
    numerator: sum:trace.pyramid.request.hits{service:test-xyz, env:test}.as_count()
      - sum:trace.pyramid.request.errors{service:test-xyz, env:test}.as_count()
  tags:
  - integration:kubernetes
  - service:test-xyz
  - env:test
  - team:sre
  - generated:kubernetes
  targetThreshold: 99500m
  timeframe: 7d
  type: metric
```

results in multiple SLOs being created in Datadog:

![CleanShot 2024-01-31 at 11 35 23@2x](https://github.com/DataDog/datadog-operator/assets/102622612/8b88411d-cef3-472c-be52-de450ed71226)

Deleting the `DatadogSLO` results in one of the SLOs being orphaned in Datadog.

**Describe what you expected:**

I expect a single `DatadogSLO` resource to result in a single SLO created in Datadog.

**Steps to reproduce the issue:**

Install the Datadog Operator via Helm (chart version `1.4.1`) with following values:

```yaml
datadogCRDs:
  crds:
    datadogSLOs: true
apiKeyExistingSecret: datadog-secret
appKeyExistingSecret: datadog-secret
datadogMonitor:
  enabled: true
datadogSLO:
  enabled: true
site: datadoghq.com
watchNamespaces:
- ""
```
Kubectl apply the example `DatadogSLO` above. 

**Additional environment details (Operating System, Cloud provider, etc):**
