### ISSUE TITLE
clusterAgent maxSurge and maxUnavailable with `kind:DatadogAgent`

### ISSUE THREAD

**Issue by marcinkubica** [DataDog/datadog-operator#1147]
**Describe what happened:**
attempted to control cluster agent maxSurge and maxUnavailable with `kind:DatadogAgent` manifest

**Describe what you expected:**
custom values applied

Seems unable to customise

**Comment by levan-m** [comment]
Thanks for submitting the issue @marcinkubica.
Could you please provide following:
*  Details about your environment
* Sample manifest 
* What you are getting
* What you expect to get

**Comment by marcinkubica** [comment]
hi @levan-m!

```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  features:
    admissionController:
      enabled: true
    apm:
      enabled: true
    clusterChecks:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    logCollection:
      containerCollectAll: false
      enabled: true
    npm:
      enabled: true
  global:
    clusterName: example-01
    credentials:
      apiSecret:
        keyName: api-key
        secretName: operator-keys
      appSecret:
        keyName: app-key
        secretName: operator-keys
    site: datadoghq.eu
  override:
    clusterAgent:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - cluster-agent
              topologyKey: kubernetes.io/hostname
      containers:
        cluster-agent:
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
      image:
        tag: 7.52.1
      replicas: 2
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
    nodeAgent:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - example
      image:
        tag: 7.52.1
```

I have a couple of gke clusters with 1 or 2 VMs. Having there 1 or 2 replicas for clusterAgent causes Pods to be unscheduled due to what I believe is rollout strategy set in Deployment generated by CRD

```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
```

I'm struggling to control maxUnavaliable/maxSurge or change to `type:Recreate`
Having checked CRD def it doesn't seem there's override possible for deployment strategy?
