### ISSUE TITLE
External Metrics / HPA integration not working

### ISSUE THREAD

**Issue by thehunt33r** [DataDog/datadog-operator#119]
**Describe what happened:**

* Deployed Datadog Operator (using the latest Datadog Operator built from master)
* Deployed a DatadogAgent with this configuration:

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  agent:
    apm:
      enabled: true
      hostPort: 8126
    config:
      collectEvents: true
      criSocket:
        criSocketPath: /var/run/containerd/containerd.sock
        useCriSocketVolume: true
      env:
      - name: DD_TAGS
        value: cluster_name:relevant-cheetah,environment:dev,region:eu-west-1,account:eu-dev
      - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
        value: "true"
      - name: DD_APM_NON_LOCAL_TRAFFIC
        value: "true"
      - name: DD_AC_EXCLUDE
        value: image:602401143452.dkr.ecr.us-west-2.amazonaws.com/cni-metrics-helper
          image:602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni image:576513738724.dkr.ecr.eu-west-1.amazonaws.com/tools/datadog-agent
          image:datadog/cluster-agent image:datadog/agent
      hostPort: 8125
      leaderElection: true
      logLevel: INFO
      tolerations:
      - operator: Exists
    image:
      name: datadog/agent:7.20.2
    log:
      enabled: true
      logsConfigContainerCollectAll: true
    process:
      enabled: true
    systemProbe:
      bpfDebugEnabled: true
      enabled: true
  clusterAgent:
    config:
      clusterChecksEnabled: true
      env:
      - name: DD_TAGS
        value: cluster_name:relevant-cheetah,environment:dev,region:eu-west-1,account:eu-dev
      - name: DD_EXTRA_CONFIG_PROVIDERS
        value: kube_services
      - name: DD_EXTRA_LISTENERS
        value: kube_services
      - name: DATADOG_HOST
        value: https://app.datadoghq.eu
      externalMetrics:
        enabled: true
      metricsProviderEnabled: true
    image:
      name: datadog/cluster-agent:1.6.0
    replicas: 2
  credentials:
    apiKey: xxxxx
    appKey: xxxxx
  site: datadoghq.eu
```

* Deployed the test Nginx manifest from https://www.datadoghq.com/blog/autoscale-kubernetes-datadog/#register-the-external-metrics-provider in `default` namespace, and the test HPA
* When describing the HPA, I get errors essentially saying that HPA can't read the metrics
```shell
$ k describe hpa nginxext
Name:                                                nginxext
Namespace:                                           default
Labels:                                              <none>
Annotations:                                         CreationTimestamp:  Wed, 08 Jul 2020 10:05:00 +0200
Reference:                                           Deployment/nginx
Metrics:                                             ( current / target )
  "nginx.net.request_per_s" (target average value):  <unknown> / 9
Min replicas:                                        1
Max replicas:                                        5
Deployment pods:                                     1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric default/nginx.net.request_per_s/&LabelSelector{MatchLabels:map[string]string{kube_container_name: nginx,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: nginx.net.request_per_s.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "nginx.net.request_per_s" in API group "external.metrics.k8s.io" in the namespace "default"
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedComputeMetricsReplicas  10m (x12 over 13m)    horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get nginx.net.request_per_s external metric: unable to get external metric default/nginx.net.request_per_s/&LabelSelector{MatchLabels:map[string]string{kube_container_name: nginx,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: nginx.net.request_per_s.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "nginx.net.request_per_s" in API group "external.metrics.k8s.io" in the namespace "default"
  Warning  FailedGetExternalMetric       3m32s (x41 over 13m)  horizontal-pod-autoscaler  unable to get external metric default/nginx.net.request_per_s/&LabelSelector{MatchLabels:map[string]string{kube_container_name: nginx,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: nginx.net.request_per_s.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "nginx.net.request_per_s" in API group "external.metrics.k8s.io" in the namespace "default"
```
* After checking the documentation provided by Datadog, I wasn't able to find any resources documented in [rbac-hpa.yaml](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/hpa-example/rbac-hpa.yaml) created.

**Describe what you expected:**

* I would expect the HPA to be able to query the external metrics API and get the metrics
* I would expect the resources described in [rbac-hpa.yaml](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/hpa-example/rbac-hpa.yaml) to be created by Datadog Operator when we configure a Cluster Agent with External Metrics enabled.

**Steps to reproduce the issue:**

* Deploy Datadog operator in a new cluster
* Deploy a Datadog Agent with `externalMetrics.enabled: true`
* Deploy the [test Nginx manifest](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/hpa-example/nginx.yaml)
* Deploy the [test HPA](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/hpa-example/hpa-manifest.yaml)
* Run `kubectl describe hpa nginxext` and you should see similar errors to what I've posted.

**Additional environment details (Operating System, Cloud provider, etc):**

* Running EKS 1.16, on AWS, with the latest AMI.
* Using site Datadoghq.eu

Wondering if I might have missed a configuration flag?
