### ISSUE TITLE
onMissingData support for monitor type "metric alert"

### ISSUE THREAD

**Issue by tath81** [DataDog/datadog-operator#1303]
**Describe what happened:**
When using the `onMissingData` for the monitor type `metric alert` the error message "invalid monitor type" is shown.

**Describe what you expected:**

**Steps to reproduce the issue:**
kubectl apply -f values.yaml

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: nodes-unavailable
  namespace: datadog
spec:
  query: "max(last_15m):sum:kubernetes_state.node.status{status:schedulable} by {kube_cluster_name} * 100 / sum:kubernetes_state.node.status{*} by {kube_cluster_name} < 80"
  type: "query alert"
  name: "[kubernetes] Monitor Unschedulable Kubernetes Nodes"
  message: "More than 20% of nodes are unschedulable on ({{kube_cluster_name.name}} cluster). \n Keep in mind that this might be expected based on your infrastructure."
  tags:
    - "integration:kubernetes"
  options:
    onMissingData: "1h"
```
**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS version 1.29
