### ISSUE TITLE
Resources on agent pods

### ISSUE THREAD

**Issue by mausch** [DataDog/datadog-operator#1306]
Hi, I noticed that the operator doesn't set any resource limits/requests by default (using `datadoghq.com/v2alpha1` `DatadogAgent`).
Setting resources is documented in https://github.com/DataDog/datadog-operator/blob/1c660295e84a49e33d9e3c5588fffbd9fb3b76d6/docs/configuration.v2alpha1.md#override .
The example mentioned there is for a "system-probe" container. However my datadog-agent pods don't have that container? 
I have containers "agent", "trace-agent", and "process-agent".
I just want to confirm that this is really how you're meant to set resources? Is the documentation out of date maybe?

Thanks

**Comment by tbavelier** [comment]
> I just want to confirm that this is really how you're meant to set resources?

That is correct, you're meant to use `[key].containers.[key].resources.requests` and `[key].containers.[key].resources.limits` at the container level.

> I have containers "agent", "trace-agent", and "process-agent".

The `system-probe` container is only an example and is not present by default as it is only required in some features such as Network Performance Monitoring. So it is normal you would only have those containers and not the `system-probe` and you'd use them in your override to give them specific resources. Here's an example you could use setting up `requests` and `limits` on the `agent` container, and only `limits` on the `trace-agent` and `process-agent`

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  override:
    nodeAgent:
      containers:
        agent:
          resources:
            requests:
              cpu: "1"
              memory: 500Mi
            limits:
              cpu: "2"
              memory: 1Gi
        trace-agent:
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
        process-agent:
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
```
