### ISSUE TITLE
Agent: OTLP Logs Support ?

### ISSUE THREAD

**Issue by drazzib** [DataDog/datadog-operator#1442]
**Describe what happened:**

With current release of datadog-operator, it seems datadog-agent pod is started with default 
`DD_OTLP_CONFIG_LOGS_ENABLED: "false"`

AFAIK, there is no way to change this default value from datadog-operator (I've checked [Configuration](https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md))

**Describe what you expected:**

As described in [Ingest OpenTelemetry logs with the Datadog Agent](https://www.datadoghq.com/blog/agent-otlp-log-ingestion/) blog post and from [OTLP Ingestion by the Datadog Agent](https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=kubernetes#enabling-otlp-ingestion-on-the-datadog-agent) reference documentation we should be able to enable this feature

FTR, this feature has already been added into [DataDog/helm-charts](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/CHANGELOG.md#3530) v3.53 release

> Add `otlp.logs.enabled` option to datadog agent to set the `DD_OTLP_CONFIG_LOGS_ENABLED` env variable.

**Comment by fanny-jiang** [comment]
Hi @drazzib, apologies about that! As a workaround, you can enable OTLP logs using `spec.override`:

```
spec:
  override:
    nodeAgent:
      env:
      - name: DD_OTLP_CONFIG_LOGS_ENABLED
        value: true
```

I've added a card to our backlog to add configurable otlp logs support.

**Comment by scottgerring** [comment]
Hey gang,

Just wanted to add that this got me too - I would've thought the [features here] would've enabled this:

* `features.otlp.receiver.protocols.grpc.enabled` - `Enable the OTLP/gRPC endpoint. Host port is enabled by default and can be disabled.`

**Comment by darylgraham** [comment]
Just a note that the [documentation](https://docs.datadoghq.com/opentelemetry/setup/otlp_ingest_in_the_agent/?tab=kubernetesoperator#enabling-otlp-ingestion-on-the-datadog-agent) for enabling `otlp` via the operator specifically mentions this feature in the example config, however that config fails due to a schema mismatch.

```yaml
features:
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
    logs:
      enabled: false
```

`.spec.features.otlp.logs: field not declared in schema`
