### ISSUE TITLE
serviceAccountAnnotations is not usable

### ISSUE THREAD

**Issue by koltunskim** [DataDog/datadog-operator#1493]
considering [documentation](https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md), I should be able to use `[key].serviceAccountAnnotations map[string]string`. This does not work as serivceAccountAnnotations object can not be parsed by the API. 

error: ` strict decoding error: unknown field "spec.override.nodeAgent.serviceAccountAnnotations"`

command ` kubectl get crd datadogagents.datadoghq.com  -o yaml | grep -i service | grep -i serviceAccountAnnotations` gives empty result. 

Chart used is datadog-operator v1.9.0

agent manifest:
```
apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
  namespace: "datadog"
spec:
  features:
    logCollection:
      containerCollectAll: true
      enabled: true
  global:
    clusterName: "redacted"
    credentials:
      apiKey: "redacted"
      appKey: "redacted"
    tags: ["env:env"]
  override:
    nodeAgent:
      serviceAccountAnnotations:
        test: "true"
      containers:
        agent:
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
```

I've tried it also with combinations with `createRbac` and `serviceAccountName` with no luck
