### ISSUE TITLE
Failing to set `spec.override.clusterAgent.createPodDisruptionBudget` - CRD spec out of date?

### ISSUE THREAD

**Issue by jess-belliveau** [DataDog/datadog-operator#1548]
I am trying to introduce a PDB for our operator controlled datadog-agents but the CR change is being rejected:

```
  override:
    clusterAgent:
      replicas: 2
      createPodDisruptionBudget: true
```

```
strict decoding error: unknown field "spec.override.clusterAgent.createPodDisruptionBudget"
```

This is a new cluster where we have deployed the `datadog-operator` via helm:

```
➜ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.6-eks-7f9249a
```

```
➜ helm list -n monitoring
NAME            	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
datadog-operator	monitoring	2       	2024-11-29 12:38:18.611971639 +0000 UTC	deployed	datadog-operator-2.3.0	1.10.0

➜ helm status datadog-operator
NAME: datadog-operator
LAST DEPLOYED: Fri Nov 29 12:38:18 2024
NAMESPACE: monitoring
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
```

As desired, the CRDs are installed by the operator - and the version for `datadogagents` matches `v2alpha1`:
```
➜ kubectl api-resources | grep -i datadog
datadogagents                       dd                         datadoghq.com/v2alpha1               true         DatadogAgent
datadogmetrics                                                 datadoghq.com/v1alpha1               true         DatadogMetric
datadogmonitors                                                datadoghq.com/v1alpha1               true         DatadogMonitor
datadogpodautoscalers               dpa                        datadoghq.com/v1alpha1               true         DatadogPodAutoscaler
```

based on this link, `v2alpha1` should include the `createPodDisruptionBudget` field: https://github.com/DataDog/datadog-operator/blob/main/config/crd/bases/v1/datadoghq.com_datadogagents.yaml#L4106

If I attempt to find the field in the deployed CRD, it appears to not be present:
```
➜ kubectl get crd datadogagents.datadoghq.com -o yaml | grep -i create
                      create:
                    createRbac:
```

Some other notes:
```
➜ kubectl get datadogagents.v2alpha1.datadoghq.com datadog

NAME      AGENT             CLUSTER-AGENT     CLUSTER-CHECKS-RUNNER   AGE
datadog   Running (8/8/8)   Running (1/1/1)                           9d
```

I'm a tad confused why this is happening and we aren't seeing the same spec for the CRD

```
➜ kubectl get crd datadogagents.datadoghq.com -o yaml | kubectl neat | head -40
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
    meta.helm.sh/release-name: datadog-operator
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: datadog-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadogCRDs
    helm.sh/chart: datadogCRDs-2.2.0
  name: datadogagents.datadoghq.com
spec:
  conversion:
    strategy: None
  group: datadoghq.com
  names:
    kind: DatadogAgent
    listKind: DatadogAgentList
    plural: datadogagents
    shortNames:
    - dd
    singular: datadogagent
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.agent.status
      name: agent
      type: string
    - jsonPath: .status.clusterAgent.status
      name: cluster-agent
      type: string
    - jsonPath: .status.clusterChecksRunner.status
      name: cluster-checks-runner
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v2alpha1
```
