### ISSUE TITLE
Any plan for a ServiceMonitor-like CRD?

### ISSUE THREAD

**Issue by sebastien-prudhomme** [DataDog/datadog-operator#1605]
Hi,

Coming from Prometheus Operator, I find it's sometime not ideal to configure Datadog integrations for Kubernetes workload by using either annotations on pods or autodiscovery in Datadog agent config.

Is there any plan to implement a CRD that would allow configuring integrations throught Kubernetes labels selectors without modifying the original workload or the Datadog agent?

**Comment by starlightromero** [comment]
I can add my 2c, since I would also like to see this feature. Currently for custom metrics, datadog annotations need to be added to a pod. Here is an example with cert-manager:

```yaml
      ad.datadoghq.com/cert-manager-controller.checks: |
        {
          "openmetrics": {
            "init_config": {},
            "instances": [
              {
                "openmetrics_endpoint": "http://%%host%%:9402/metrics",
                "namespace": "cert_manager"
                "metrics": [
                  "certificate.expiration_timestamp",
                  "certificate.ready_status",
                  "certificate.renewal_timestamp"
                ],
                "tags": [
                  "component:controller",
                  "service:cert-manager",
                  "cluster_name:example-cluster",
                  "business:infra",
                  "env:prod"
                ]
              }
            ]
          }
        }
```

This is a lot of data to cram into an annotation. Furthermore, because annotations can be any string, there is no type or schema validation. This can lead to misconfigurations which become cumbersome to debug.

In a similar fashion, this is why the Kubernetes `Ingress` [resource is being deprecated](https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/) in favor of the Gateway API.

> The breadth and flexibility of Ingress NGINX has caused maintenance challenges. Changing expectations about cloud native software have also added complications. What were once considered helpful options have sometimes come to be considered serious security flaws, such as the ability to add arbitrary NGINX configuration directives via the "snippets" annotations. Yesterday’s flexibility has become today’s insurmountable technical debt.

The quote above addresses the security flaws of snippet annotations, but as many Kubernetes cluster maintainers can attest to, the sheer amount of Ingress annotations that could add up caused maintenance issues as well.

Instead, Datadog should create a CRD called `DatadogCustomMetric` which can reference a pod. Something like:

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogCustomMetric
metadata:
  name: example-metric
  namespace: example
spec:
  container:
    endpoint: /metrics  # optional, defaults to /metrics
    name: cert-manager-controller  # required
    port: 8080  # optional, defaults to 8080
  datadogNamespacePrefix: cert_manager
  metrics:  # optional, defaults to all metrics
   - metricName: certificate.expiration_timestamp
   - metricName: certificate.ready_status
     datadogMetricName: certificate.ready  # optional, defaults to metricName
   - metricName: certificate.renewal_timestamp
  podSelector:  # required
    matchLabels:
      app: cert-manager
  tags:  # optional
    component:controller
    service:cert-manager
    cluster_name:example-cluster
    business:infra
    env:prod
```
