### ISSUE TITLE
Reconciler error - unable to delete ServiceAccount from the store because it was not found

### ISSUE THREAD

**Issue by dac73** [DataDog/datadog-operator#1675]
Hi, getting set of errors in cluster-operator which I can't figure out.
Operator version: `1.11.1`
Helm version: `2.5.1`

DataDog Agent conf:
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  override:
...
    clusterAgent:
      createRbac: false
      createPodDisruptionBudget: false
      serviceAccountName: datadog-cluster-agent-sa
      replicas: 2
...
```
Operator install:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: datadog
spec:
  interval: 5m
  timeout: 1h
  releaseName: datadog-operator
  chart:
    spec:
      chart: datadog-operator
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog
      version: 2.5.1
```
Service account and needed permissions are setup (cluster agent works and doesn't throw errors if I manually update the deployment).

Errors on operator:
```
{"level":"DPANIC","ts":"2025-02-10T14:07:19.159Z","logger":"controllers.DatadogAgent","msg":"non-string key argument passed to logging, ignoring all later arguments","datadogagent":{"name":"datadog","namespace":"datadog"},"invalid key":"clusterAgent"}
{"level":"INFO","ts":"2025-02-10T14:07:19.159Z","logger":"controllers.DatadogAgent","msg":"Deleting RBACs for %s","datadogagent":{"name":"datadog","namespace":"datadog"}}
{"level":"ERROR","ts":"2025-02-10T14:07:19.159Z","msg":"Reconciler error","controller":"datadogagent","controllerGroup":"datadoghq.com","controllerKind":"DatadogAgent","DatadogAgent":{"name":"datadog","namespace":"datadog"},"namespace":"datadog","name":"datadog","reconcileID":"47f4fe37-abbd-43c1-a3ad-b149b4865be6","error":"unable to delete ServiceAccount from the store because it was not found: datadog/datadog-cluster-agent-sa","errorCauses":[{"error":"unable to delete ServiceAccount from the store because it was not found: datadog/datadog-cluster-agent-sa","errorCauses":[{"error":"unable to delete ServiceAccount from the store because it was not found: datadog/datadog-cluster-agent-sa","errorCauses":[{"error":"unable to delete ServiceAccount from the store because it was not found: datadog/datadog-cluster-agent-sa"}]}]}]}
```
