### ISSUE TITLE
Fargate sidecar injector uses a different secret than the one defined on the CRD

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/datadog-operator#1688]
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
spec:
  global:
    clusterName: my-cluster
    credentials:
      apiSecret:
        keyName: api-key
        secretName: datadog-keys
      appSecret:
        keyName: app-key
        secretName: datadog-keys
    registry: public.ecr.aws/datadog
```

fargate injected sidecar
```
  - env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          key: api-key
          name: datadog-secret

```
