### ISSUE TITLE
Error/Warning on init-config container about missing DD_API_KEY env var

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/datadog-operator#1689]
init-config You must set an DD_API_KEY environment variable to run the Datadog Agent container

This should be populated automatically.

```
  global:
    clusterName: my-cluster
    credentials:
      apiSecret:
        keyName: api-key
        secretName: datadog-secret
      appSecret:
        keyName: app-key
        secretName: datadog-secret
```
