### ISSUE TITLE
Error creating dashboard: is_read_only deprecation

### ISSUE THREAD

**Issue by matthew-parry-cc** [DataDog/datadog-operator#1707]
Hi, we are seeing the following error when attempting to update or create dashboards:
```
 Message:               error updating dashboard: 400 Bad Request: {"errors":["The is_read_only attribute is no longer supported.                     https://docs.datadoghq.com/dashboards/guide/is-read-only-deprecation/"]}
```
```
 Message:               error creating dashboard: 400 Bad Request: {"errors":["The is_read_only attribute is no longer supported.                     https://docs.datadoghq.com/dashboards/guide/is-read-only-deprecation/"]}
```
This occurs when attempting to create any dashboard, even a simple/blank one which works via the UI , for example:
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogDashboard
metadata:
  name: test
spec:
  title: My Test Dashboard
  description: null
  widgets: "[]"
  templateVariables: []
  layoutType: ordered
  notifyList: []
  reflowType: fixed
```
We are using the latest version of the operator `gcr.io/datadoghq/operator:1.12.1`. Has there been any API updates which might be causing this?

Thanks.
