### ISSUE TITLE
system-probe container breaks in recent versions of k8s due to seccomp/apparmor profile

### ISSUE THREAD

**Issue by jpetazzo** [DataDog/datadog-operator#1726]
After upgrading a Kubernetes cluster from 1.29 to 1.32, I noticed that the Datadog agent pods were in a weird state - specifically, one of the 4 containers (`system-probe`) wasn't starting.

The Kubernetes events (shown e.g. by investigating the pod with `kubectl describe`) showed the following error message:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed:
unable to start container process: error during container init: unable to setup user: resource temporarily unavailable: unknown
```

(Note that the exact message might be different with other container engines.)

The datadog-agent pods had an annotation `container.apparmor.security.beta.kubernetes.io/system-probe=unconfined`, but the `system-probe` container also had a `securityContext` section that looked like:
```yaml
securityContext:
  seccompProfile:
    type: Localhost
    localhostProfile: system-probe
```

I *suppose* that the agent pods broke because back in 1.29, the annotation was enough to run the `system-probe` container in `unconfined` mode; but in 1.32, the annotation is deprecated. (See e.g. [Kubernetes AppArmor documentation page][kaadoc].)

I *suppose* that the `securityContext` generated by the Datadog Operator would work if we had the `system-probe` profile installed locally on our nodes; but that's not the case. (I don't know why the profile is missing; the [Datadog Operator documentation][dodoc] doesn't say anything about these profiles, so I don't know if they're meant to be installed automatically or if we should take care of installing them ourselves.)

The solution, for us, was to add a series of overrides to the `DatadogAgent` Custom Resource:
```yaml
...
spec:
  override:
    nodeAgent:
      containers:
        system-probe:
          securityContext:
            capabilities:
              add:
              - CHOWN
              - DAC_READ_SEARCH
              - IPC_LOCK
              - NET_ADMIN
              - NET_BROADCAST
              - NET_RAW
              - SYS_ADMIN
              - SYS_PTRACE
              - SYS_RESOURCE
            seccompProfile:
              type: Unconfined
```

Note that unfortunately, as soon as we override anything in the `securityContext` section, it clears the existing values - meaning that it removes all capabilities. This means that we have to re-add all the capabilities needed by the agent. (I don't know if all these capabilities are needed; I just copy-pasted the ones that were added by default in the DaemonSet created by the Datadog Operator.)

I don't know what's the proper solution here (again, I have no idea whether the problem comes from something exotic in our setup or a missing bit in the Datadog Operator), but I hope this issue will help others if they face the same situation!

For what it's worth, this particular cluster is running k3s.

[dodoc]: https://docs.datadoghq.com/containers/datadog_operator/ 
[kaadoc]: https://kubernetes.io/docs/tutorials/security/apparmor/
