### ISSUE TITLE
Unable to use DatadogAgent's global.secretBackend.roles

### ISSUE THREAD

**Issue by Denton-L** [DataDog/datadog-operator#1752]
I am attempting to configure Datadog to read some cross-namespace secrets. The DatadogAgent is in the namespace `datadog` and the secret I am attempting to read is in the namespace `database`. I have the following DatadogAgent resource defined:

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName:
    registry: public.ecr.aws/datadog
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    secretBackend:
      command: '/readsecret_multiple_providers.sh'
      #enableGlobalPermissions: true
      roles:
        - namespace: database
          secrets:
            - vestadb-datadog-secret
...TRUNCATED
```

and it seems like the `*-secret-backend` ClusterRole is not being created properly. Looking at the logs for the datadog-operator, I see the following log lines (abridged):

```json
{
    "msg": "Reconciler error",
    "error": "unable to get: database/database-datadog-secret-backend because of unknown namespace for the cache",
    "errorCauses": [
        {
            "error": "unable to get: database/database-datadog-secret-backend because of unknown namespace for the cache"
        },
        {
            "error": "unable to get: database/database-datadog-secret-backend because of unknown namespace for the cache"
        }
    ]
}
```

According to the documentation,

> Note: Each namespace in the roles list must also be configured in the WATCH_NAMESPACE or DD_AGENT_WATCH_NAMESPACE environment variable on the Datadog Operator deployment.

but it is not very apparent where or how this is supposed to be set. I briefly looked through the codebase but I was unable to ascertain how to set it. Some more clarity would be appreciated.

For the record, `global.secretBackend.enableGlobalPermissions` works but I'd like to avoid using it for security purposes.
