### ISSUE TITLE
operator 1.13.0 doesn't set up NodeAgents?

### ISSUE THREAD

**Issue by sean1615** [DataDog/datadog-operator#1813]
First did a helm upgrade to v1.130 to the datadog-operator and thought something was amiss when my datadog-agent pods disappeared. so did a full uninstall and reinstalled the datadog operator into the observability namespace and when I do a kubectl get pods -n observability, the only pods that show are the datadog-cluster-agent and the datdog-operator.
Cluster Agent Version: 7.63.3
Datadog Operator Version: 1.13.0

Are they needed anymore?

values.yaml used on the kubectl apply part:
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: observability
spec:
  global:
    clusterName: dmm-multi-tenant-cluster-qa
    credentials:
      apiSecret:
        keyName: api-key
        secretName: datadog-secret
      appSecret:
        keyName: app-key
        secretName: datadog-secret
    registry: public.ecr.aws/datadog
    tags:
      - cluster:********
      - env:********
      - aws_account:********
  features:
    apm:
      enabled: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    processDiscovery:
      enabled: true
    oomKill:
      enabled: true
    tcpQueueLength:
      enabled: true
    ebpfCheck:
      enabled: true
    apm:
      enabled: true
    cspm:
      enabled: true
    cws:
      enabled: true
    npm:
      enabled: true
    usm:
      enabled: true
    dogstatsd:
      unixDomainSocketConfig:
        enabled: true
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
    remoteConfiguration:
      enabled: true
    sbom:
      enabled: true
    serviceDiscovery:
      enabled: true
    gpu:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    orchestratorExplorer:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    admissionController:
      enabled: true
    externalMetricsServer:
      enabled: true
```
