### ISSUE TITLE
Init container container resource limitation

### ISSUE THREAD

**Issue by jasonwangnanjing** [DataDog/datadog-operator#1832]
Hi Expert

https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md 
this document only describe how to limit resource on node agent. But I noticed for every service there are two init containers created

1. datadog-init-apm-inject
2. datadog-lib-java-init**

And both of are request 1 CPU and 1G memory. How could I control their resource limit?

**Comment by tbavelier** [comment]
Hello @jasonwangnanjing ,

These init containers are managed by the cluster Agent and not the operator while using the Single Step APM instrumentation feature: https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=kubernetespreview.
I believe their limits should be based on what your application pods are requesting: https://github.com/DataDog/datadog-agent/pull/30266. This will not impact their scheduling: https://github.com/DataDog/datadog-agent/blob/f376a75844c46d97c580b25151ccff815e9eabf1/pkg/clusteragent/admission/mutate/autoinstrumentation/auto_instrumentation.go#L361-L375.

You can nonetheless define the requests/limits yourself by using the corresponding parameters: https://github.com/DataDog/datadog-agent/blob/f376a75844c46d97c580b25151ccff815e9eabf1/pkg/config/setup/config.go#L810-L811. These should be applied as environment variables on the cluster Agent, thus in your `DatadogAgent` manifest:
```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog-agent
spec:
  global:
    [...]
  features:
    [...]
  override:
    clusterAgent:
      env:
      - name: DD_ADMISSION_CONTROLLER_AUTO_INSTRUMENTATION_INIT_RESOURCES_CPU
        value: "100m"
      - name: DD_ADMISSION_CONTROLLER_AUTO_INSTRUMENTATION_INIT_RESOURCES_MEMORY
        value: "128Mi"
```

If this is an issue/not behaving as expected, please raise it in the https://github.com/DataDog/datadog-agent repository, as this feature is controlled by the cluster Agent and not the operator.
