### ISSUE TITLE
DD_APP_KEY is not added to cluster-agent when appKeyExistingSecret is added after initial install

### ISSUE THREAD

**Issue by erulabs** [DataDog/datadog-operator#1858]
Hello!

  It appears that if one adds appKeyExistingSecret _after_ installation, the operator never gets around to updating the cluster-agent deployment with the valueFrom environment variable. Cluster-agent continues to work properly but `DatadogMetrics` fail due to: `fail to create datadog client for metrics provider, error: missing the api/app key pair to query Datadog`.

```
        - name: DD_APP_KEY
          valueFrom:
            secretKeyRef:
              key: app-key
              name: datadog-secret
```

I tried deleting the cluster-agent deployment and letting the operator re-assert it, but it still did not appear. 

My operator values:

```
site: datadoghq.com

apiKeyExistingSecret: datadog-secret
appKeyExistingSecret: datadog-secret

image:
  # image.repository -- Repository to use for Datadog Operator image
  repository: gcr.io/datadoghq/operator
  # image.tag -- Define the Datadog Operator version to use
  tag: 1.12.1
  # image.pullPolicy -- Define the pullPolicy for Datadog Operator image
  pullPolicy: IfNotPresent

logLevel: info
installCRDs: true
datadogCRDs:
  crds:
    # datadogCRDs.crds.datadogAgents -- Set to true to deploy the DatadogAgents CRD
    datadogAgents: true
    # datadogCRDs.crds.datadogMetrics -- Set to true to deploy the DatadogMetrics CRD
    datadogMetrics: true
    # datadogCRDs.crds.datadogMonitors -- Set to true to deploy the DatadogMonitors CRD
    datadogMonitors: true
    # datadogCRDs.crds.datadogSLOs -- Set to true to deploy the DatadogSLO CRD
    datadogSLOs: false

datadogMonitor:
  # datadogMonitor.enabled -- Enables the Datadog Monitor controller
  enabled: true

watchNamespaces:
  - ""

datadogAgent:
  # datadogAgent.enabled -- Enables Datadog Agent controller
  enabled: true
```

Note that in this case, `appKeyExistingSecret` was added after initial install. They have been applied:

```
helm -n datadog get values datadog --all | fgrep -i existingsecret
apiKeyExistingSecret: datadog-secret
appKeyExistingSecret: datadog-secret
```
