### ISSUE TITLE
Configuring trace shipping

### ISSUE THREAD

**Issue by tbenade** [DataDog/datadog-operator#1894]
Could I please get some help in validating the following settings are supported by the operator. We have found setting these settings have had no impact on how the traces are forwarded and are always shipped directly to Datadog regardless. 

```
DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_ENABLED: "true"
DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_URL: "http://our-vector-aggragator-service"
```

The forwarding of metrics though by setting the following envars works as expected.

```
DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED
DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_URL
```

This is our live manifest running in production.

```
containers:
    - command:
        - agent
        - run
      env:
        - name: DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_ENABLED
          value: 'true'
        - name: DD_OBSERVABILITY_PIPELINES_WORKER_METRICS_URL
          value: https://vector-aggregator.somewhere:8282
        - name: DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_ENABLED
          value: 'true'
        - name: DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_URL
          value: https://vector-aggregator.somewhere:8282
        - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_ENABLED
          value: 'true'
        - name: DD_OBSERVABILITY_PIPELINES_WORKER_LOGS_URL
          value: https://vector-aggregator.somewhere:8282
      image: gcr.io/datadoghq/agent:7.64.3
```
Where in the code are these setting applied to the running agent?

Thank you.

**Comment by khewonc** [comment]
Hi @tbenade, it looks like these env vars are all set in the core agent container in your agent pod. Can you try adding the `DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_*` env vars to the [trace-agent container](https://github.com/DataDog/datadog-operator/blob/ffadec3264ecdf34774f5a63f3a668ba400e4ded/api/datadoghq/common/types.go#L54)? Here's an example of how that can be configured in the operator:

```yaml
spec:
  override:
    nodeAgent:
      containers:
        trace-agent:
          env:
          - name: DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_ENABLED
            value: 'true'
          - name: DD_OBSERVABILITY_PIPELINES_WORKER_TRACES_URL
            value: https://vector-aggregator.somewhere:8282
```

If that doesn't work, can you open up a [support ticket](https://docs.datadoghq.com/help/) for this? Our team unfortunately aren't familiar with the internals of observability pipeline worker, but the support team should be able to look into it and direct it to the correct team for further investigation if needed
