### ISSUE TITLE
DatadogAgent.spec.override.image field validation fails

### ISSUE THREAD

**Issue by jwtracy** [DataDog/datadog-operator#1937]
I'm trying to specify a "full" variant of the agent image for OTEL and other functionality

Documentation:

```
➜ k explain datadogagent.spec.override.image
GROUP:      datadoghq.com
KIND:       DatadogAgent
VERSION:    v2alpha1

FIELD: image <Object>


DESCRIPTION:
    <empty>
FIELDS:
  jmxEnabled    <boolean>
    <no description>

  name  <string>
    <no description>

  pullPolicy    <string>
    <no description>

  pullSecrets   <[]Object>
    <no description>

  tag   <string>
    <no description>
```

Relevant section of my DatadogAgent config:

```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog-system
spec:
  override:
    image:
      name: gcr.io/datadoghq/agent
      tag: 7.66.0-full
  ...
```

Validation errors on apply:

```
DatadogAgent/datadog-system/datadog dry-run failed: failed to create typed patch object (datadog-system/datadog; datadoghq.com/v2alpha1, Kind=DatadogAgent): .spec.override.image.tag: field not declared in schema
```

Let me know if I'm doing something wrong or propose a fix to the validating webhook for this CRD.
