### ISSUE TITLE
cluster-checks-runner gets deployed without asking for it

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#208]
Datadog operator version 0.4.0

**Describe what happened:**

I got 2 replicas of the checkrunner, but I didn't ask for it in the definition of my `DatadogAgent` object

**Describe what you expected:**

Only the node agent and the cluster agent gets deployed

**Steps to reproduce the issue:**

1. Create a token secret as: `kubectl create secret generic datadog --from-literal=token='<ThirtyX2XcharactersXlongXtoken>'` (because it doesn't get automatically created due to issue #207 )
2. Apply the following DatadogAgent definition:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-app-key
      keyName: app-key
  agent:
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
    image:
      name: "datadog/agent:latest"
    apm:
      enabled: true
    process:
      enabled: true
    log:
      enabled: true
    config:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  clusterAgent:
    image:
      name: "datadog/cluster-agent:latest"
    config:
      clusterChecksEnabled: true
    replicas: 1
```

At the end I got the following deployments:

```
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
datadog-cluster-agent           1/1     1            1           73m
datadog-cluster-checks-runner   1/2     2            1           73m
```

I wouldn't expect the datadog-cluster-checks-runner deployment to be created

**Additional environment details (Operating System, Cloud provider, etc):**
