### ISSUE TITLE
Error validating data

### ISSUE THREAD

**Issue by mikalai-t** [DataDog/datadog-operator#211]
Hello.

Omit some info from the issue template, because don't know what "Info page" is.

**Describe what happened:**
Got the error trying to deploy Datadog Agent with Operator:
```shell
running kubectl: exit status 1, stderr: error: error validating \"STDIN\": error validating data: ValidationError(DatadogAgent.spec.agent.process): unknown field \"processCollection\" in com.datadoghq.v1alpha1.DatadogAgent.spec.agent.process; if you choose to ignore these errors, turn validation off with --validate=false"
```

**Describe what you expected:**
Agent instance is created in desired configuration

**Steps to reproduce the issue:**
1. Deploy Datadog Operator using `Helm Operator`:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: monitoring
spec:
  chart:
    repository: "https://helm.datadoghq.com"
    name: "datadog-operator"
    version: "0.4.0"
  values:
    # logLevel -- Set Datadog Operator log level (debug, info, error, panic, fatal)
    logLevel: "error"

    serviceAccount:
      # serviceAccount.name -- The name of the service account to use. If not set name is generated using the fullname template
      name: datadog-operator

    # installCRDs -- Set to true to deploy the Datadog's CRDs
    installCRDs: true

    datadog-crds:
      crds:
        # datadog-crds.crds.datadogAgents -- Set to true to deploy the DatadogAgents CRD
        datadogAgents: true
        # datadog-crds.crds.datadogMetrics -- Set to true to deploy the DatadogMetrics CRD
        datadogMetrics: true
```
2. Deploy Datadog agent resource:
```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog-agent
  namespace: monitoring
spec:
  # see:
  #   * https://github.com/DataDog/datadog-operator/blob/master/docs/secret_management.md
  credentials:
    apiKeyExistingSecret: datadog-api-key

  agent:
    image:
      # Define the image to use Use "datadog/agent:latest" for Datadog Agent 6 Use "datadog/dogstatsd:latest" for
      # Standalone Datadog Agent DogStatsD6 Use "datadog/cluster-agent:latest" for Datadog Cluster Agent
      name: "gcr.io/datadoghq/agent:latest"
    config:
      # Enable this to start event collection from the Kubernetes API
      # ref: https://docs.datadoghq.com/agent/kubernetes/event_collection/
      collectEvents: true

    # ref: https://github.com/DataDog/docker-dd-agent#tracing-from-the-host
    apm:
      # Enable this to enable APM and tracing, on port 8126
      enabled: false

    # ref.: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup
    log:
      # Enables this to activate Datadog Agent log collection.
      enabled: true
      # Enable this to allow log collection for all containers.
      logsConfigContainerCollectAll: true

    # ref: https://docs.datadoghq.com/graphing/infrastructure/process/#kubernetes-daemonset
    process:
      # Enable this to activate the process Agent and live container monitoring.
      # Note: /etc/passwd is automatically mounted to allow username resolution.
      enabled: true
      # Enable this to activate the process collection in addition to container collection.
      processCollection: true

    rbac:
      # Used to configure RBAC resources creation
      create: true
      # Used to set up the service account name to use Ignored if the field Create is true
      serviceAccountName: datadog-agent

    # ref: https://docs.datadoghq.com/graphing/infrastructure/process/#kubernetes-daemonset
    systemProbe:
      # Enable this to activate live process monitoring. Note: /etc/passwd is automatically mounted to allow username
      # resolution.
      enabled: true
      # BPFDebugEnabled logging for kernel debug
      bpfDebugEnabled: true

  # The site of the Datadog intake to send Agent data to. Set to 'datadoghq.eu' to send data to the EU site.
  site: datadoghq.eu
```

**Additional environment details (Operating System, Cloud provider, etc):**
1. AWS EKS
2. EKS optimized AMI x64
