### ISSUE TITLE
Auto-created secret should get an auto-generated name

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#225]
(this is on operator `0.5.0-rc2`)

Right now, if a user describes their agent deployment like this:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiKey: <DATADOG_API_KEY>
    appKey: <DATADOG_APP_KEY>
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
```

the operator will create a secret called `datadog` (like the object name), but this way it is fairly easy to have a conflict in names.

Actually, if I try to create that object and I already have that secret created, the operator logs won't show any errors (probably it should) and the failure happens at the Datadog daemonset level:

```
    state:
      waiting:
        message: couldn't find key api_key in Secret default/datadog
        reason: CreateContainerConfigError
```

Ideally, we would do as Kubernetes does when automatically creating objects, where it does something like `<name>-autogeneratednumber`

**Comment by arapulido** [comment]
Because creating  a new secret will always be with the object name, this definition will fail, for example:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiSecret:
      secretName: datadog
      keyName: api-key
    appSecret:
      secretName: datadog
      keyName: app-key
  agent:
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
    image:
      name: "datadog/agent:latest"
    apm:
      enabled: true
    process:
      enabled: true
    log:
      enabled: true
    config:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  clusterAgent:
    image:
      name: "datadog/cluster-agent:latest"
    config:
      clusterChecksEnabled: true
    replicas: 1
```

As it will try to read the token from that secret, but it won't be there:

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m15s                 default-scheduler  Successfully assigned default/datadog-cluster-agent-655f5d476d-2hk5d to node01
  Warning  Failed     78s (x12 over 3m13s)  kubelet, node01    Error: couldn't find key token in Secret default/datadog
  Normal   Pulled     67s (x13 over 3m13s)  kubelet, node01    Container image "datadog/cluster-agent:latest" already present on machine
```
