### ISSUE TITLE
`clusterName` option doesn't get forwarded to the `process-agent`

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#229]
**Describe what happened:**

Using `0.5.0-rc2` I wanted to enable the OrchestratorExplorer, I used this `DatadogAgent` config:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: katacoda
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
    image:
      name: "datadog/agent:latest"
    apm:
      enabled: true
    process:
      enabled: true
      processCollectionEnabled: true
    log:
      enabled: true
    config:
      logLevel: info
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  clusterAgent:
    config:
      logLevel: debug
    image:
      name: "datadog/cluster-agent:latest"
  features:
    orchestratorExplorer:
      enabled: true
```

But, when the process-agent starts, it logs the following:

```
2021-02-16 11:20:37 UTC | PROCESS | WARN | (pkg/process/config/config.go:382 in NewAgentConfig) | Failed to auto-detect a Kubernetes cluster name. Pod collection will not start. To fix this, set it manually via the cluster_name config option
```

It looks like the DCA is picking the cluster name correctly, as I get the right objects in the Deployment, Nodes, etc. views, but nothing in the Pods view.

**Describe what you expected:**

The process-agent uses the value for `clusterName` as the cluster name and Pod collection starts correctly

**Steps to reproduce the issue:**

1. Deploy operator 0.5.0-rc2
2. Deploy the `DatadogAgent` config above
