### ISSUE TITLE
Configure Cluster Checks dynamically

### ISSUE THREAD

**Issue by PSanetra** [DataDog/datadog-operator#241]
It would be nice to have a `ClusterCheck` CRD, which could be deployed independently from the Cluster Agent deployment. Currently it is only possible to configure such a check via a `ConfigMap` and reference this `ConfigMap` in the `DatadogAgent` resource of the Cluster Agent.

This way the Cluster Agent could be deployed centrally without knowing about application specific cluster checks (such as checks on applications, running outside of the cluster).

**Comment by clamoriniere** [comment]
Hi @PSanetra,

Thanks for opening this issue. Indeed we are evaluating the possibility to configure cluster check with a dedicated CRD.

For now, what you describe is already possible thanks to [Auto-discovery Annotations](https://docs.datadoghq.com/agent/cluster_agent/endpointschecks/) attached to a dedicated Kubernetes Service.

For example to target a service running outside a kubernetes cluster. you can create an empty K8s Service with the check configuration in a Datadog auto-discovery annotations. 


```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-check-exposer
  namespace: my-app
  annotations:
    ad.datadoghq.com/endpoints.check_names: '["my-check"]'
    ad.datadoghq.com/endpoints.init_configs: '[{}]'
    ad.datadoghq.com/endpoints.instances: |
      [
        {
          "host": "https://my-check.com/metrics",
          "port": "6379"
        }
      ]
spec:
  clusterIP: "None"
```

It is less native than a CRD, but you can already create, update cluster check configurations without redeploying the cluster-agent.

Let me know if my answer has helped you to improve your monitoring configuration.
