### ISSUE TITLE
Error running the pod check for the Orchestration Explorer

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#242]
This is using the operator `0.5.0`:

I tried enabled the Orchestration Explorer, and all the collection works, except for the pod check in the `process-agent` where I get the following error:

```
2021-02-25 09:35:34 UTC | PROCESS | DEBUG | (pkg/util/kubernetes/clustername/clustername.go:145 in GetClusterID) | Cluster ID env variable DD_ORCHESTRATOR_CLUSTER_ID is missing, calling the Cluster Agent
2021-02-25 09:35:34 UTC | PROCESS | ERROR | (collector.go:109 in runCheck) | Unable to run check 'pod': unexpected status code from cluster agent: 404
```

This is the `DatadogAgent` object that I am using:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  clusterName: katacoda
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    env:
      - name: DD_KUBELET_TLS_VERIFY
        value: "false"
    image:
      name: "datadog/agent:latest"
    apm:
      enabled: true
    process:
      enabled: true
    log:
      enabled: true
    config:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      logLevel: debug
  clusterAgent:
    image:
      name: "datadog/cluster-agent:latest"
  features:
    orchestratorExplorer:
      enabled: true
```
