### ISSUE TITLE
Unable to get kubeStateMetricsCore feature working

### ISSUE THREAD

**Issue by dixonwille** [DataDog/datadog-operator#253]
**datadog-cluster-checks-agent (7.26.0)**
```
=========
Collector
=========

  Running Checks
  ==============
    No checks have run yet

  Loading Errors
  ==============
    kubernetes_state_core
    ---------------------
      Core Check Loader:
        Could not configure check kubernetes_state_core: temporary failure in apiserver, will retry later: check resources failed: event collection: "events is forbidden: User \"system:serviceaccount:datadog:datadog-cluster-checks-runner\" cannot list resource \"events\" in API group \"\" at the cluster scope"

      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so

      Python Check Loader:
        unable to import module 'kubernetes_state_core': No module named 'kubernetes_state_core'
```

**DatadogAgent File (Operator version 0.5.0)**

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiSecret:
      keyName: api-key
      secretName: datadog
    appSecret:
      keyName: app-key
      secretName: datadog-appkey
  features:
    kubeStateMetricsCore:
      enabled: true
    orchestratorExplorer:
      enabled: true
    prometheusScrape:
      enabled: true
  agent:
    image:
      name: gcr.io/datadoghq/agent:latest
    log:
      enabled: true
      containerCollectUsingFiles: true
      logsConfigContainerCollectAll: true
    process:
      enabled: true
      processCollection: true
    systemProbe:
      enabled: true
      bpfDebugEnabled: true
    security:
      compliance:
        enabled: true
      runtime:
        enabled: false
    config:
      leaderElection: false
      criSocket:
        criSocketPath: /var/run/dockershim.sock
      tolerations:
        - operator: Exists 
  clusterAgent:
    image:
      name: gcr.io/datadoghq/cluster-agent:1.11.0-rc2
    config:
      clusterChecksEnabled: true
      collectEvents: true
      admissionController:
        enabled: true
        mutateUnlabelled: false
  clusterCheckRunner:
    image:
      name: gcr.io/datadoghq/agent:latest
```

**Describe what happened:**

Whenever the `DatadogAgent` resource is applied, we get all the pods that are expected. The Cluster Agent reports that it is dispatching the check:

```
2021-03-04 21:29:02 UTC | CLUSTER | INFO | (pkg/clusteragent/clusterchecks/dispatcher_main.go:138 in add) | Dispatching configuration kubernetes_state_core:314b92a3f57cdafa to node CORRECT_EC2_HOSTNAME_HERE
```

But the Cluster Checks Runner fails with the log below:

```
2021-03-04 21:29:03 UTC | CORE | INFO | (pkg/autodiscovery/config_poller.go:95 in poll) | cluster-checks provider: collected 1 new configurations, removed 0
2021-03-04 21:29:03 UTC | CORE | ERROR | (pkg/collector/corechecks/loader.go:72 in Load) | core.loader: could not configure check kubernetes_state_core: temporary failure in apiserver, will retry later: check resources failed: event collection: "events is forbidden: User \"system:serviceaccount:datadog:datadog-cluster-checks-runner\" cannot list resource \"events\" in API group \"\" at the cluster scope"
2021-03-04 21:29:03 UTC | CORE | ERROR | (pkg/collector/scheduler.go:248 in GetChecksFromConfigs) | Unable to load the check: unable to load any check from config 'kubernetes_state_core'
```

**Steps to reproduce the issue:**

As far as I can tell, all that is required to reproduce this is the following file

```yaml
features:
    kubeStateMetricsCore:
      enabled: true
clusterAgent:
    image:
      name: "datadog/cluster-agent:1.11.0-rc2"
    config:
      clusterChecksEnabled: true
clusterChecksRunner:
    image:
      name: "datadog/agent:7.26.0"
```

**Additional environment details (Operating System, Cloud provider, etc):**

OS: Bottlerocket AMI from AWS
Cloud: AWS EKS

**Notes**

- I tried changing version of the clusterChecksRunner but it seems to always use the `latest` tag.
- I am using `1.11.0-rc2` because of #242
- kubernetes version 1.19
