### ISSUE TITLE
Panic occurs: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kskumgk63** [DataDog/datadog-operator#305]
**Describe what happened:**

I've been trying to deploy datadog agents through `datadog-operator`, but `datadog-operator` occurs a panic.

```
github.com/DataDog/datadog-operator/controllers/datadogagent.isComplianceEnabled(...)
	/workspace/controllers/datadogagent/utils.go:175
github.com/DataDog/datadog-operator/controllers/datadogagent.buildClusterAgentClusterRole(0xc00040f680, 0xc0005f60e0, 0x12, 0x0, 0x0, 0x44)
	/workspace/controllers/datadogagent/clusteragent.go:1298 +0x4b8
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).createClusterAgentClusterRole(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0005f60e0, 0x12, 0x0, 0x0, 0xc0002d6000, 0x1ef2060, ...)
	/workspace/controllers/datadogagent/clusteragent.go:838 +0x74
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).manageClusterAgentRBACs(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0007b6600, 0x0, 0x0, 0x0)
	/workspace/controllers/datadogagent/clusteragent.go:737 +0x48f
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).manageClusterAgentDependencies(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0005ca870, 0x1bc6b20, 0x2, 0x2, 0xc0006f3970)
	/workspace/controllers/datadogagent/clusteragent.go:244 +0x510
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).reconcileClusterAgent(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0005ca870, 0x30, 0x1b7fa00, 0xc00030f801, 0xc0005ca870)
	/workspace/controllers/datadogagent/clusteragent.go:36 +0x74
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).internalReconcile(0xc000451440, 0x1f2c3c0, 0xc0005ca750, 0xc0006270b0, 0x10, 0xc000627084, 0x4, 0x1baea00, 0x10, 0x1b10c40, ...)
	/workspace/controllers/datadogagent/controller.go:131 +0x4f3
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).Reconcile(0xc000451440, 0x1f2c3c0, 0xc0005ca750, 0xc0006270b0, 0x10, 0xc000627084, 0x4, 0x1baea00, 0xc0005ca750, 0x1a9bc60, ...)
	/workspace/controllers/datadogagent/controller.go:67 +0x8e
github.com/DataDog/datadog-operator/controllers.(*DatadogAgentReconciler).Reconcile(0xc00062e050, 0x1f2c3c0, 0xc0005ca750, 0xc0006270b0, 0x10, 0xc000627084, 0x4, 0xc0005ca750, 0x40a3df, 0xc000030000, ...)
	/workspace/controllers/datadogagent_controller.go:140 +0x7b
```

<details>
<summary>full panic log</summary>

```
{ "level": "ERROR", "logger": "klog", "msg": "Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 561 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1a9d760, 0x2bc9ff0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1a9d760, 0x2bc9ff0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/DataDog/datadog-operator/controllers/datadogagent.isComplianceEnabled(...)
	/workspace/controllers/datadogagent/utils.go:175
github.com/DataDog/datadog-operator/controllers/datadogagent.buildClusterAgentClusterRole(0xc00040f680, 0xc0005f60e0, 0x12, 0x0, 0x0, 0x44)
	/workspace/controllers/datadogagent/clusteragent.go:1298 +0x4b8
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).createClusterAgentClusterRole(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0005f60e0, 0x12, 0x0, 0x0, 0xc0002d6000, 0x1ef2060, ...)
	/workspace/controllers/datadogagent/clusteragent.go:838 +0x74
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).manageClusterAgentRBACs(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0007b6600, 0x0, 0x0, 0x0)
	/workspace/controllers/datadogagent/clusteragent.go:737 +0x48f
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).manageClusterAgentDependencies(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0005ca870, 0x1bc6b20, 0x2, 0x2, 0xc0006f3970)
	/workspace/controllers/datadogagent/clusteragent.go:244 +0x510
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).reconcileClusterAgent(0xc000451440, 0x1f35c20, 0xc0005c2b80, 0xc00040f680, 0xc0005ca870, 0x30, 0x1b7fa00, 0xc00030f801, 0xc0005ca870)
	/workspace/controllers/datadogagent/clusteragent.go:36 +0x74
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).internalReconcile(0xc000451440, 0x1f2c3c0, 0xc0005ca750, 0xc0006270b0, 0x10, 0xc000627084, 0x4, 0x1baea00, 0x10, 0x1b10c40, ...)
	/workspace/controllers/datadogagent/controller.go:131 +0x4f3
github.com/DataDog/datadog-operator/controllers/datadogagent.(*Reconciler).Reconcile(0xc000451440, 0x1f2c3c0, 0xc0005ca750, 0xc0006270b0, 0x10, 0xc000627084, 0x4, 0x1baea00, 0xc0005ca750, 0x1a9bc60, ...)
	/workspace/controllers/datadogagent/controller.go:67 +0x8e
github.com/DataDog/datadog-operator/controllers.(*DatadogAgentReconciler).Reconcile(0xc00062e050, 0x1f2c3c0, 0xc0005ca750, 0xc0006270b0, 0x10, 0xc000627084, 0x4, 0xc0005ca750, 0x40a3df, 0xc000030000, ...)
	/workspace/controllers/datadogagent_controller.go:140 +0x7b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004ce000, 0x1f2c300, 0xc000396380, 0x1b0c920, 0xc00000c7e0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004ce000, 0x1f2c300, 0xc000396380, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1f2c300, 0xc000396380)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000ba0f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006f3f50, 0x1ef2280, 0xc0005ca690, 0xc000396301, 0xc0001141e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ba0f50, 0x3b9aca00, 0x0, 0x1, 0xc0001141e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1f2c300, 0xc000396380, 0xc0005c2af0, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1f2c300, 0xc000396380, 0xc0005c2af0, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x4e7
", "ts": "2021-05-17T02:02:07Z" } 
```
</details>

**Describe what you expected:**

`datadog-operator` deploys datadog agent, clusteragent. 

**Steps to reproduce the issue:**

1. `helm install`
```
helm repo add datadog https://helm.datadoghq.com
helm install my-datadog-operator datadog/datadog-operator
```
2. apply a following manifest.

<details>
<summary>agent.yaml</summary>

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: test
  namespace: datadog
spec:
  credentials:
    apiSecret:
      keyName: api-secret
      secretName: datadog
    appSecret:
      keyName: app-secret
      secretName: datadog
  agent:
    additionalAnnotations:
      sidecar.istio.io/inject: "false"
    additionalLabels:
      app: datadog-agent
    image:
      name: gcr.io/datadoghq/agent:7.27.0
    apm:
      enabled: true
    process:
      enabled: true
      processCollectionEnabled: true
    log:
      enabled: true
    systemProbe:
      bpfDebugEnabled: true
    security:
      compliance:
        enabled: true
      runtime:
        enabled: false
    config:
      tolerations:
      - operator: Exists
    env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog
          key: api-key
  clusterAgent:
    additionalAnnotations:
      sidecar.istio.io/inject: "false"
    image:
      name: gcr.io/datadoghq/cluster-agent:1.12.0
    config:
      externalMetrics:
        enabled: true
    replicas: 1
    rbac:
      create: true
```
</details>

**Additional environment details (Operating System, Cloud provider, etc):**

gke version: `v1.18.17-gke.700`
