### ISSUE TITLE
Enable DD_APM_NON_LOCAL_TRAFFIC and hostPort by default if apm=true

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#312]
If a user has a DatadogAgent configuration that says: `apm:true` is very confusing that the hostPort is not enable by default and that `DD_APM_NON_LOCAL_TRAFFIC` is not true by default.

This is the behaviour of the Helm chart, and removing it for the operator is very confusing.

**Comment by clamoriniere** [comment]
Hello @arapulido 

It should not be the case.
A user should only have to set

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
#...
spec:
  #...
  agent:
    # ...
    apm:
      enabled: true
```
 
to enable APM with the hostPort.

**Comment by clamoriniere** [comment]
I just checked, and you are write it doesn't work as expected.

right now it we want to to have the hostport expose you need to specify a port in the config

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
#...
spec:
  #...
  agent:
    # ...
    apm:
      enabled: true
      hostPort: 8126
```

We will fix it soon.
