### ISSUE TITLE
CRI Check Fails on EKS with Bottlerocket

### ISSUE THREAD

**Issue by wavemoran** [DataDog/datadog-operator#327]
**Output of the info page (if this is a bug)**

```
    cri
    ---
      Instance ID: cri [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/cri.d/conf.yaml.default
      Total Runs: 134
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 62ms
      Last Execution Date : 2021-06-25 17:10:15 UTC (1624641015000)
      Last Successful Execution Date : Never
      Error: temporary failure in criutil, will retry later: try delay not elapsed yet
      No traceback
      Warning: Error initialising check: temporary failure in criutil, will retry later: try delay not elapsed yet
```

**Describe what happened:**

CRI checks are failing on EKS running Bottlerocket.

```
2021-06-25 17:13:16 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:301 in work) | Error running check cri: temporary failure in criutil, will retry later: failed to dial: context deadline exceeded
2021-06-25 17:13:30 UTC | CORE | WARN | (pkg/collector/corechecks/checkbase.go:165 in Warnf) | Error initialising check: temporary failure in criutil, will retry later: try delay not elapsed yet
2021-06-25 17:13:30 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:301 in work) | Error running check cri: temporary failure in criutil, will retry later: try delay not elapsed yet
```

**Describe what you expected:**

CRI checks should pass.

**Steps to reproduce the issue:**

- Create an EKS cluster with Bottlerocket worker nodes.
- Deploy Datadog operator
- Deploy agents with the below config with the additional `cirSocketPath` as outlined in https://docs.datadoghq.com/agent/kubernetes/distributions/?tab=operator#EKS

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: monitoring
spec:
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
    apm:
      enabled: false
    process:
      enabled: true
      processCollectionEnabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
      containerCollectUsingFiles: true
    config:
      criSocket:
        criSocketPath: /run/dockershim.sock
      collectEvents: true
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
```

**Additional environment details (Operating System, Cloud provider, etc):**

EKS v1.20 on AWS with Bottlerocket AMI bottlerocket-aws-k8s-1.20-x86_64-v1.1.1-28c4e013.

**Comment by wavemoran** [comment]
I opened a support ticket and received the following solution:

The issue stems from the default value of the `DockerSocketPath` field and this condition: https://github.com/DataDog/datadog-operator/blob/v0.6.0/controllers/datadogagent/utils.go#L914-L918. Since there is a default value, the code will always validate the if and mount the wrong path. 

There has been a PR to fix this issue, the fix will be shipped in the version 0.7 of the operator.

In the meantime could you please explicitly set dockerSocketPath to null:

```yaml
config: 
      criSocket: 
        criSocketPath: /run/dockershim.sock 
        dockerSocketPath: null
```
