### ISSUE TITLE
Missing some default pod tags

### ISSUE THREAD

**Issue by wavemoran** [DataDog/datadog-operator#337]
**Describe what happened:**

Some default or "out of the box" tags are missing from pods (and maybe other places).

**Describe what you expected:**

Compared to manual agent deployment, certain tags are missing that are used to populate default facets for log searches. Missing tags that I have noticed in particular include `kubernetescluster` (used to populate the Kubernetes > Cluster facet) and `container_name` (populates log header "blocks").

**Steps to reproduce the issue:**

Agents deployed with the following configuration:

```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: monitoring
spec:
  clusterName: staging-eks01
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
    apm:
      enabled: false
    process:
      enabled: true
      processCollectionEnabled: true
    log:
      enabled: true
      logsConfigContainerCollectAll: true
      containerCollectUsingFiles: true
    config:
      criSocket:
        criSocketPath: /run/dockershim.sock
        dockerSocketPath: null
      collectEvents: true
      leaderElection: true
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
    config:
      clusterChecksEnabled: true
      admissionController:
        enabled: true
        mutateUnlabelled: false
  features:
    kubeStateMetricsCore:
      enabled: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

Bottlerocket OS 1.1.2, EKS 1.20, Agent (v7.29.0)
