### ISSUE TITLE
Feature request: Configuring the agent via helm-chart values

### ISSUE THREAD

**Issue by pcothenet** [DataDog/datadog-operator#346]
**Describe what happened:**

The current recommended way to install the operator is:
1) Deploy using a helm chart (helm chart values apply to the operator only)
2) `kubectl` to apply the config to the agent

**Describe what you expected:**

Being able to configure the agent by passing the agent config directly to the operator helm chart. This would save a step and having to save another configuration elsewhere.

(I'm fairly new to k8s / helm so I might be off base here, consider this newbie feedback)

**Additional environment details (Operating System, Cloud provider, etc):**

We use `helm_release` in terraform to manage our Helm charts.

**Comment by clamoriniere** [comment]
Hello @pcothenet,

We don't propose the creation of the DatadogAgent CR in our helm chart, because we were thinking that it will be a 1-to-1 mapping between the `values.yaml` and the `DatadogAgent.spec`. Or the `values.yaml` file will look like:

```yaml
#...

datadogAgent:
  # create: set to true to create a DatadogAgent instance automatically
  create: true
  # name: use to set the name of the DatadogAgent instance
  name: dd-agent
  # spec: put the `DatadogAgent.spec` configuration here
  spec: 
      
```

What I can recommend you if you need a helm chart to manage the deployment of the DatadogAgent CR is to create new helm chart:
* `helm create my-datadog-agent-config`
* put our "datadog/datadog-operator" chart as [dependency](https://helm.sh/docs/helm/helm_dependency/): 
   ```yaml 
   # Chart.yaml file
   dependencies:
    - name: datadog-operator
      version: "=0.7.0"
      repository: https://helm.datadoghq.com
   ```
* Define your `values.yaml` with the configuration granularity you would like to configure the agent.

Please let us know if this solution fit your needs.

Thanks
Cedric
