### ISSUE TITLE
Add support for log monitors

### ISSUE THREAD

**Issue by alexadriaanse** [DataDog/datadog-operator#388]
The [monitor documentation](https://github.com/DataDog/datadog-operator/blob/main/docs/datadog_monitor.md) states that currently "only metric alerts, query alerts, and service checks are supported." I'd love to see datadog-operator add support for managing log monitors as well.

For example, I'm trying to create a monitor that looks like this:
```yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  finalizers:
  - finalizer.monitor.datadoghq.com
  name: ...
  namespace: datadog
spec:
  message: ...
  name: ...
  options: {}
  query: logs("...").index("main").rollup("count").by("service").last("15m") > 0
  tags: ...
  type: log alert
```

But currently the operator generates an error for this resource with the following message:
```
monitor type log alert not supported
```
