### ISSUE TITLE
Custom Resources for DataDog resources

### ISSUE THREAD

**Issue by mzizzi** [DataDog/datadog-operator#4]
I apologize in advance if this isn't the right place for these sorts of questions of if I missed this on road map elsewhere.

Has there been any discussion around the DataDog operator handling custom resources for Monitors, Dashboards, etc? Idea being that I'd like to template and provision DataDog resources using the same kube manifests/charts that I deploy the rest of my infrastructure with. This is similar to how the prometheus operator supports [PrometheusRule resources](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md).

I previously hacked out this concept as part of playing with a python operator framework: https://github.com/mzizzi/dogkop

I'd imagined being able to create DataDog Monitor resources as follows:
```yaml
apiVersion: datadog.mzizzi/v1
kind: Monitor
metadata:
  name: my-monitor
spec:
  type: metric alert
  query: avg(last_5m):sum:system.net.bytes_rcvd{host:host0} > 100
  name: Bytes received on host0
  message: We may need to add web hosts if this is consistently high.
  tags:
    - foo:bar
  options:
    notify_no_data: True,
    no_data_timeframe: 20
```

This could be extremely powerful when coupled with the DataDog agent's OpenMetrics/Prometheus checks.
