### ISSUE TITLE
Ignoring Unwanted Resources in APM

### ISSUE THREAD

**Issue by gavnate** [DataDog/datadog-operator#431]
**Describe what happened:**
Was wondering how folks could exclude traces like health-checks at the agent level using this operator? Something similar to [this](https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml#trace-agent-configuration-options).

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, EKS.

**Comment by kyanar** [comment]
This is actually mentioned in the [documentation](https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.md)

The key you'll need to set is agent.apm.env - your yaml will kind of look like this:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: kube-system
spec:
  registry: public.ecr.aws/datadog
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  agent:
    apm:
      enabled: true
      env:
      - name: DD_APM_IGNORE_RESOURCES
        value: "GET /healthcheck"
```
