### ISSUE TITLE
NewHostDelay is deprecated and doesn't work. NewGroupDelay should be used.

### ISSUE THREAD

**Issue by jnogol** [DataDog/datadog-operator#525]
**Describe what happened:**
[NewHostDelay](https://github.com/DataDog/datadog-operator/blob/main/controllers/datadogmonitor/monitor.go#L114-L116)
is [Deprecated](https://github.com/DataDog/datadog-api-client-go/blob/ac14372d2bc7820a099fecb2e29d78ec92d47575/api/v1/datadog/model_monitor_options.go#L57-L58) in favor of [NewGroupDelay](https://github.com/DataDog/datadog-api-client-go/blob/ac14372d2bc7820a099fecb2e29d78ec92d47575/api/v1/datadog/model_monitor_options.go#L50-L51).

This is making that creation of monitors always default to 60 seconds no matter the value `NewHostDelay` has.

**Describe what you expected:**

I expected my monitor to be created with the value I set `NewHostDelay` to (300 seconds in this case). 

**Steps to reproduce the issue:**
- Try to create a monitor like this

``` yaml
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: pod-insufficient-replicas
spec:
  name: "Deployment has insufficient replicas"
  query: "avg(last_15m):avg:kubernetes_state.deployment.replicas_desired{*} - avg:kubernetes_state.deployment.replicas_available{*} > 2"
  type: "metric alert"
  message: |
    My message
  options:
    requireFullWindow: false
    newHostDelay: 300
```

- Go to your created monitor in https://app.datadoghq.com/
- Find that, under "3 - Set Alert Conditions/Advanced Options/Evaluation Options" this is what is set "Before evaluating new groups, wait 60 seconds."

**Additional environment details (Operating System, Cloud provider, etc):**
- Datadog Operator 0.8.0
- Datadog Operator Helm Chart 0.8.2
- AWS
