### ISSUE TITLE
APM socket not created

### ISSUE THREAD

**Issue by ghost** [DataDog/datadog-operator#598]
**Output of the info page (if this is a bug)**

We installed the operator helm chart, created the secret and deployed the agent with the following `datadog-agent.yaml`:

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  credentials:
    apiSecret:
      secretName: datadog-secret
      keyName: api-key
    appSecret:
      secretName: datadog-secret
      keyName: app-key
  site: datadoghq.eu
  agent:
    image:
      name: "gcr.io/datadoghq/agent:latest"
    apm:
      enabled: true
    log:
      enabled: true
    process:
      enabled: true
    config:
      collectEvents: true
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:latest"
    config:
      externalMetrics:
        enabled: true
      admissionController:
        enabled: true
        mutateUnlabelled: true
```

Following the docs, we would expect that the `/var/run/datadog/apm.socket` is created. 
Screenshot of the docs:
<img width="826" alt="Screenshot 2022-08-19 at 08 06 27" src="https://user-images.githubusercontent.com/98735803/185554233-6bca72c3-20b3-44c9-8051-731a276eba61.png">

**Describe what happened:**

Only the ` /var/run/datadog/statsd/statsd.sock` is created and mounted.

**Describe what you expected:**

1. The socket `/var/run/datadog/apm.socket` being created and mounted.
2. The socket `/var/run/datadog/statsd/statsd.sock` to be created on the default path `/var/run/datadog/dsd.socket`
3. The configuration variables `agent.apm.hostSocketPath ` and `agent.apm.socketPath` to be included in the list https://docs.datadoghq.com/containers/kubernetes/operator_configuration/.
 
**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes: v1.22.11
Cloud provider: AWS
Datadog-operator chart: 0.8.6

I also tried adding the undocumented setting: `spec.agent.apm.unixDomainSocket.enabled: true` based on this reported issue: https://github.com/DataDog/datadog-operator/issues/585, without success.
