### ISSUE TITLE
cannot patch "datadogagents.datadoghq.com" with kind CustomResourceDefinition when updating operator via Helm & Terraform

### ISSUE THREAD

**Issue by GenPage** [DataDog/datadog-operator#602]
**Output of the info page (if this is a bug)**
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.datadog-operator[0].helm_release.datadog-operator will be updated in-place
  ~ resource "helm_release" "datadog-operator" {
        id                         = "datadog"
        name                       = "datadog"
      + pass_credentials           = false
      ~ version                    = "0.7.10" -> "0.8.6"
        # (26 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

module.datadog-operator[0].helm_release.datadog-operator: Modifying... [id=datadog]
module.datadog-operator[0].helm_release.datadog-operator: Still modifying... [id=datadog, 10s elapsed]
╷
│ Error: cannot patch "datadogagents.datadoghq.com" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "datadogagents.datadoghq.com" is invalid: spec.validation: Forbidden: top-level and per-version schemas are mutually exclusive
│
│   with module.datadog-operator[0].helm_release.datadog-operator,
│   on modules/datadog-operator/main.tf line 62, in resource "helm_release" "datadog-operator":
│   62: resource "helm_release" "datadog-operator" {
│
╵
Releasing state lock. This may take a few moments...
ERRO[0131] 1 error occurred:
        * exit status 1
```

**Describe what happened:**
Trying to update to latest helm chart to get newer agent versions

**Describe what you expected:**
Operator to apply successfully

**Steps to reproduce the issue:**
Upgrade from 0.7.10 -> 0.8.6

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.20
Terraform 1.0.8

Agent CRD config (templated with Terraform)
```
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: ${namespace}
spec:
  agent:
    config:
      collectEvents: true
      leaderElection: true
      tolerations:
      - operator: Exists
      podLabelsAsTags: {
        "*": "kube_%%label%%"
      }
      tags:
      %{~ for tag in metric_tags ~}
        - ${tag}
      %{~ endfor ~}
    image:
      name: ${agent_image_tag}
    log:
      enabled: ${log_monitoring}
    process:
      enabled: true
      processCollectionEnabled: true
    systemProbe:
      enabled: true
    security:
      compliance:
        enabled: ${security_monitoring}
      runtime:
        enabled: ${security_monitoring}
  clusterAgent:
    enabled: true
    config:
      collectEvents: true
      clusterChecksEnabled: true
      externalMetrics:
        enabled: true
      volumeMounts:
        - mountPath: "/etc/datadog-agent/conf.d/mysql.d/"
          name: mysql-conf
          readOnly: true
        - mountPath: "/etc/datadog-agent/conf.d/postgres.d/"
          name: postgres-conf
          readOnly: true
      volumes:
        - name: mysql-conf
          projected:
            sources:
              - secret:
                  name: mysql-${db}-conf
        - name: postgres-conf
          projected:
            sources:
              - secret:
                  name: pgsql-${db}-conf
    image:
      name: ${cluster_agent_image_tag}
  clusterName: ${cluster_name}
  credentials:
    apiSecret:
      secretName: ${cred_secret_name}
      keyName: api-key
    appSecret:
      secretName: ${cred_secret_name}
      keyName: app-key
  features:
    kubeStateMetricsCore:
      enabled: true
    networkMonitoring:
      enabled: ${network_monitoring}
    orchestratorExplorer:
      enabled: true
      extraTags:
        - "datacenter:${datacenter}"
    prometheusScrape:
      enabled: false
  registry: public.ecr.aws/datadog
```

Datadog Operator config:
```
---
apiKeyExistingSecret: ${secret_name}
appKeyExistingSecret: ${secret_name}
datadogMonitor:
  enabled: ${enable_datadog_monitor}
supportExtendedDaemonset: ${enable_extended_daemonset}
registry: public.ecr.aws/datadog
watchNamespaces:
  - ""
```
