### ISSUE TITLE
Operator does not honor DD_SITE

### ISSUE THREAD

**Issue by deas** [DataDog/datadog-operator#623]
in `values.yaml` of the operator chart, it reads:

```yaml
# site -- The site of the Datadog intake to send data to (documentation: https://docs.datadoghq.com/getting_started/site/)

## Set to 'datadoghq.com' to send data to the US1 site (default).
## Set to 'datadoghq.eu' to send data to the EU site.
## Set to 'us3.datadoghq.com' to send data to the US3 site.
## Set to 'us5.datadoghq.com' to send data to the US5 site.
## Set to 'ddog-gov.com' to send data to the US1-FED site.
site:  # datadoghq.com

# dd_url -- The host of the Datadog intake server to send Agent data to, only set this option if you need the Agent to send data to a custom URL

## Overrides the site setting defined in "site".
dd_url:  # <DATADOG_API_ENDPOINT>
```

I was setting `site: datadoghq.eu`, and expected the operator to use the EU endpoint. That's not the case. It uses the default US endpoint - at least for monitors so I ended up with 403.

The docs right above `dd_url` was confusing me even more, so I did not use that when in fact - after reading through the sources, it was solving me issue.

I think operator should use `site` in context of monitor and potentially other custom resources as well.
