### ISSUE TITLE
Helm Charts for release candidates

### ISSUE THREAD

**Issue by k4r1** [DataDog/datadog-operator#649]
We'd like to be able to try out future releases in our cluster - in particular [v1.0.0-rc.3](https://github.com/DataDog/datadog-operator/releases/tag/v1.0.0-rc.3).

We've tried using the latest [operator helm chart](https://github.com/DataDog/helm-charts/tree/main/charts/datadog-operator) and overriding the image tag, as well as experimenting with some [other settings](https://github.com/DataDog/helm-charts/pull/798) (including manually installing the `v2alpha1` CRDs ourselves) to see if we can get it to work - to no avail. 

---
Are you able to point me in the right direction to get a working helm chart for this release?

And Is there a way to do this in the general case?

**Comment by CharlyF** [comment]
Hey @k4r1 - I did not expect users to start trying out the 1.0.0 given that we are in the QA phase, I am more than happy to help!
I am currently updating the documentation actually to allow the deployment of the operator via the helm chart (more specifically around adding the cert manager to migrate). 
But I am curious, can you tell me about your use case? 
- Are you doing a fresh install?
- What are the arguments that you are using?
- Can you share what info you have about it not working? (is the CRD installed? Is v2 stored and served? Is the operator pod up?)

**Comment by k4r1** [comment]
Thanks for the quick response! Yes it's a fresh install.

I'd like to enable OTLP receivers on the DataDog agents provisioned by the operator, this feature was implemented [recently](https://github.com/DataDog/datadog-operator/pull/597) but it hasn't made its way into an official release yet.

When I deploy v1.0.0.rc-3, firstly it's unhappy about the v2 CRD not existing:
```
{"level":"ERROR","ts":"2022-11-23T13:59:41Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"DatadogAgent.datadoghq.com","error":"no matches for kind \"DatadogAgent\" in version \"datadoghq.com/v2alpha1\""}
```

To fix that I tried setting:
```
migration:
  datadogAgents:
    # enabled: false # Will be used when we add the option to add the webhookConversion field in the CRD.
    version: "v2alpha1"
```

But in fact that didn't work, it looks like our cluster uses the `apiextensions.k8s.io/v1beta1` version which wasn't patched by your [PR](https://github.com/DataDog/helm-charts/pull/798).

So in the end we have to set `installCRDs: false` for the operator, pull in `datadog-crds` to install the monitoring and metrics CRDs, and then manually apply a CRD which we have modified to set the v2alpha1 to stored and served.

The error about the CRD version goes away, but then the agent starts crashing with
```

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
28
	panic: runtime error: invalid memory address or nil pointer dereference
27
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e0ea9]
26
25
goroutine 609 [running]:
24
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x73?})
23
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:55 +0xd8
22
panic({0x19566e0, 0x2cd4b60})
21
	/usr/local/go/src/runtime/panic.go:838 +0x207
20
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).getCredentialsV2(0xc000643b50?, 0xc000643a20)
19
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:582 +0x69
18
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).setupV2(0xc00052ca80)
17
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:253 +0x238
16
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).connectToDatadogAPI(0xc00052ca80)
15
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:295 +0x58
14
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x18, 0xc000600000})
13
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:220 +0x1b
12
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1e7ec50?, 0xc000560840?}, 0xc0006b7dd0?)
11
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:233 +0x57
10
k8s.io/apimachinery/pkg/util/wait.poll({0x1e7ec50, 0xc000560840}, 0x10?, 0xf4a805?, 0xc000a070a0?)
9
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:580 +0x38
8
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x1e7ec50, 0xc000560840}, 0x10?, 0xc000600000?)
7
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:545 +0x49
6
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc00052ca80?, 0xc00098b950?, 0x0?)
5
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:536 +0x7c
4
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).start(0xc00052ca80, 0x0?)
3
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:157 +0x10c
2
created by github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*ForwardersManager).Register
1
	/workspace/pkg/controller/utils/datadog/forwarders_manager.go:66 +0x2a5
```

I realise this is a release candidate! I guess my question is more along the lines of "is there a happy path for installing rc versions?", or is it a bit of a cat and mouse game every time?

**Comment by k4r1** [comment]
Yes those helm chart versions do match what we’re using, so even when the CRD is stored and served, that crash can still happen? What would be the fix?

**Comment by CharlyF** [comment]
okay so then my next assumption is that you already have or have deployed a DatadogAgent resource that is of v1alpha1 type. If that is the case, the best way to to use the conversion webhook (which I am currently documenting), but if it's a fresh install I would delete this resource and create a v2alpha1 one.
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    otlp:
      receiver:
        protocols:
          http:
            enabled: true
            endpoint: "0.0.0.0:4317" // default
```

Let me know if you have trouble with the deletion/creation of the custom resource, we have faced an issue internally that we believe to be on the ETCD side. If in the process you get a message such as:
```
The DatadogAgent "datadog" is invalid:
* status.conditions.reason: Required value
* status.conditions.message: Required value
```
let me know (we are currently investigating a proper fix).

**Comment by k4r1** [comment]
You're exactly right - it turns out that although I'd updated the CRDs, I was still deploying the agent manifest in the old format, which was causing the error I posted above.

I guess once 1.0.0 graduates to a full release it will fail with a nice error message, although it's to be expected when it's still in an early stage!

FWIW here's the manifest that got things working for me:
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    clusterName: ...
    kubelet:
      tlsVerify: false
    site: datadoghq.eu
  features:
    apm:
      enabled: true
      unixDomainSocketConfig:
        enabled: false
    liveProcessCollection:
      enabled: true
    otlp:
      receiver:
        protocols:
          http:
            enabled: true
          grpc:
            enabled: true
  override:
    nodeAgent:
      tolerations:
        - operator: Exists
      securityContext:
        runAsUser: 101
      volumes:
        - emptyDir: {}
          name: datadog-tmp
      volumeMounts:
        - mountPath: /tmp
          name: datadog-tmp
    clusterAgent:
      env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      nodeSelector: { ... }
      securityContext:
        runAsGroup: 0
        runAsUser: 1
      tolerations:
        [ ... ]
    clusterChecksRunner:
      tolerations:
        [ ... ]
```

If anyone else comes down this path, the new Agent config format is partially documented [here](https://github.com/DataDog/datadog-operator/blob/f8546b176b1163cdf59b2ff84681841b28b97b06/docs/configuration.v2alpha1.md) although it's incomplete. There's also the [OpenAPI specification](https://github.com/DataDog/helm-charts/blob/ad9522de31ebae47c97392916161747d996aabe4/charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml#L5827) which can help, although it doesn't quite contain all of the spec either. The rest can only be gleaned from the code or by asking Datadog devs directly, and in my experience they've been more than happy to help - so kudos for that @CharlyF!

Looking forward to seeing this one released, the new config format is much cleaner 👌 Thanks again for your help!
