### ISSUE TITLE
Dogstatsd does not have a hostPort

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#667]
**Output of the info page (if this is a bug)**
(Not sure how to obtain this)

**Describe what happened:**
On v1alpha1 CRD, metrics collection does not configure a hostPort (required per the conventional configuration of connecting statsds to hostip:8125)
For a counterexample, APM does.

**Describe what you expected:**
When I enable `dogstatsd` port 8125 should be bound to a host port (or at least have the option) so that the recommended configuration will work

**Steps to reproduce the issue:**
Enable dogstatsd
Observe that the port is created as follows:

```
      ports:
        - name: dogstatsdport
          containerPort: 8125
          protocol: UDP
```

Conspicuously missing is `hostPort: 8125`

**Additional environment details (Operating System, Cloud provider, etc):**
EKS 1.22

**Comment by JCMais** [comment]
For people coming here from google, if you are using v2alpha1, all you gotta do is:
```yaml
kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  features:
    dogstatsd:
      hostPortConfig:
        enabled: true
    // ...
```
