### ISSUE TITLE
Add DD_LOG_FORMAT_JSON option to operator CRD

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#668]
I have been using `DD_LOG_FORMAT_JSON` to make the datadog stack output structured logs, but it seems that in `v2alpha1` of the CRD, there is no ability to set env vars, which means I need this surfaced as a feature.

**Comment by levan-m** [comment]
Hello, 

Thanks for submitting the question! 

There is a way to supply env vars in `v2alpha` and I apologize this is missing from our [documentation](https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md); we are working on the doc update here #665.

Env vars can be defined at a component level, or container level within the component. Below sample for defining it for `agent` container within `nodeAgent`: 
```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  override:
    nodeAgent:
      containers:
        agent:
          env:
          - name: DD_WHATEVER
            value: true
```

Please note that `override` and `containers` are maps which can be configured with below keys 

https://github.com/DataDog/datadog-operator/blob/cbeaee3354b2ee825246d9276ee91ac6a6046d02/apis/datadoghq/v2alpha1/datadogagent_types.go#L16-L26

https://github.com/DataDog/datadog-operator/blob/cbeaee3354b2ee825246d9276ee91ac6a6046d02/apis/datadoghq/common/v1/types.go#L67-L95


Env var structs in code:
[Component env vars](https://github.com/DataDog/datadog-operator/blob/main/apis/datadoghq/v2alpha1/datadogagent_types.go#L779-L786)
[Container env vars](https://github.com/DataDog/datadog-operator/blob/main/apis/datadoghq/v2alpha1/datadogagent_types.go#L888-L894)

I'll close the issue, feel free to reopen it if you have any further questions.
