### ISSUE TITLE
Unable to Activate CoreDNS Auto-Discovery via ConfigMap

### ISSUE THREAD

**Issue by daviddyball** [DataDog/datadog-operator#670]
I'm attempting to enable `coredns` auto-discovery for my environment using the agent config, but for some reason `agent status` doesn't show `coredns` as a configured.

Context: We use `kops` to deploy our clusters and it manages the `coredns` deployment, so we are unable to apply labels/annotations to do auto-discovery using the K8s API.

**Describe what happened:**

Attempted to use `spec.agent.config.confd` to read auto-discovery config from a `ConfigMap` but it doesn't seem to load.

**Describe what you expected:**

I would expect auto-discovery to find and use the config to enable monitoring of CoreDNS.

**Steps to reproduce the issue:**

1. I created a `ConfigMap` called `datadog-confd-config` like so:
   ```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: datadog-confd-config
    data:
      coredns: |-
        ad_identifiers:
        - coredns
        - coredns-coredns           <--- This is the name of our mirrored copy of the image
        init_config:
        instances:
        - prometheus_url: "http://%%host%%:9153/metrics"
    ```

2. I edited my `DatadogAgent` resource to include the new config:
    ```
    apiVersion: datadoghq.com/v1alpha1
    kind: DatadogAgent
    metadata:
      name: datadog-agent
    spec:
      <-- cut -->
      agent:
        config:
          confd:
            configMapName: datadog-confd-config
            items:
            - key: coredns
              path: coredns.d/auto_conf.yaml
          criSocket:
            criSocketPath: /var/run/containerd/containerd.sock
      <-- end -->
    ```

3. Once applied I can `kubectl exec` into one of the `agent` containers in a `Pod/datadog-agent` instance and see that the config has been injected:
    ```
    root@datadog-agent-td78q:/# cat conf.d/coredns.d/auto_conf.yaml
    ad_identifiers:
    - coredns
    - coredns-coredns
    init_config:
    instances:
    - prometheus_url: "http://%%host%%:9153/metrics"
    ```

4. Unfortunately `coredns` is still not listed in the auto-discovery items when running `agent status`
    ```
    =============
    Autodiscovery
    =============
      Enabled Features
      ================
        containerd
        cri
        kubernetes
    ```

**Additional environment details (Operating System, Cloud provider, etc):**

Environment: `kops-`controlled Kubernetes on AWS
Operator: `datadog-operator-7.40.1`

**Comment by daviddyball** [comment]
Update: Datadog support resolved this by advising me to use the following:

`ConfigMap`
```
data:
  coredns.yaml: |-                    <--- Added `.yaml` to the file name
    ad_identifiers:
    - coredns
    - coredns-coredns
    init_config:
    instances:
    - prometheus_url: "http://%%host%%:9153/metrics"
```

`DatadogAgent`
```
spec:
  agent:
    config:
      confd:
        configMapName: datadog-confd-config
        <- Cut out the "items:" key completely ->
```

This resulted in `/conf.d/coredns.yaml` being created and getting picked up by the agent.

I'm a bit confused by this behaviour because all the examples include the `items:` key and are used to specifically place files in the respective `/conf.d/<integration>.d/` folders, but the working config from above puts `coredns.yaml` at the same level as `coredns.d` 🤔
