### ISSUE TITLE
datadogmonitor name doesn't work with names longer than 35 chars

### ISSUE THREAD

**Issue by arias-m** [DataDog/datadog-operator#671]
Creating datadogmonitors with metadata:name longer than 35 chars, the monitor is created but the operator is not able to manage it.
It tries to reconcile it and fails throwing an ERROR in the logs, saying the monitor already exists, which is true cause the operator was the one that created it. If I try to delete it using kubectl, it deletes the object in k8s but it is not able to delete the monitor in datadog. 

I expect names longer than 35 chars being handled properly.

To reproduce the issue, current version I use is 0.8.1,  just assign a 36 chars name to the datadogmonitor object and create it.
You should get the following output in the operator logs and then, you can delete it using kubectl delete datadogmonitor.

```
{"level":"INFO","ts":"2022-12-21T16:46:15Z","logger":"controllers.DatadogMonitor","msg":"Reconciling DatadogMonitor","datadogmonitor":"datadog/mac-datadog-p95responsetime-bentest1"}
{"level":"ERROR","ts":"2022-12-21T16:46:15Z","logger":"controllers.DatadogMonitor","msg":"error creating monitor","datadogmonitor":"datadog/mac-datadog-p95responsetime-bentest1","error":"error creating monitor: 400 Bad Request: {\"errors\":[\"Duplicate of an existing monitor_id:106264774 org_id:569146\"]}"}
```

**Comment by martijnvdp** [comment]
Got the same issue

**Comment by martijnvdp** [comment]
Dont think it has to do with the length of the name in the spec, i've tested a bunch think it has something to do with the monitor_id assignment instead, It only seems to be an issue when the monitor is created for the first time 

and a workaround is deleting the created monitor manually from datadag, and re-apply the manifest

**Comment by levan-m** [comment]
Hello, thanks for submitting the issue. I can't reproduce it; in fact I'm able to create monitor with a long name using below manifest (original taken from Datadog Monitor [doc](https://github.com/DataDog/datadog-operator/blob/main/docs/datadog_monitor.md)). Error provided above doesn't indicate that name length is the issue. 

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: datadog-monitor-test-some-looooooooong-name-monitor
spec:
  query: "avg(last_10m):avg:system.disk.in_use{*} by {host} > 0.5"
  type: "metric alert"
  name: "Test monitor made from DatadogMonitor"
  message: "We are running out of disk space!"
  tags:
    - "test:datadog"
```

Are you trying to create two identical monitors with different `metadata.name`s?
