### ISSUE TITLE
Add setting spec.agent.log.useHttp to forward logs over HTTPS

### ISSUE THREAD

**Issue by ppennanen** [DataDog/datadog-operator#68]
**Describe what happened:**

There seems to be now way to configure datadog-agent to [export logs over http](https://docs.datadoghq.com/logs/guide/log-collection-troubleshooting-guide/#outbound-traffic-on-port-10516-is-blocked). This makes it difficult to export logs when port `10516` is blocked.

**Describe what you expected:**

A `useHttp` field in the `datadogagents.datadoghq.com` `spec.agent.log` section:

```
...
            agent:
                log:
                  description: Log Agent configuration
                  properties:
                    containerLogsPath:
                      description: 'This to allow log collection from container log
                        path. Set to a different path if not using docker runtime.
                        ref: https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/?tab=k8sfile#create-manifest
                        Default to `/var/lib/docker/containers`'
                      type: string
                    enabled:
                      description: 'Enables this to activate Datadog Agent log collection.
                        ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup'
                      type: boolean
                    logsConfigContainerCollectAll:
                      description: 'Enable this to allow log collection for all containers.
                        ref: https://docs.datadoghq.com/agent/basic_agent_usage/kubernetes/#log-collection-setup'
                      type: boolean
                    podLogsPath:
                      description: This to allow log collection from pod log path.
                        Default to `/var/log/pods`
                      type: string
                    tempStoragePath:
                      description: This path (always mounted from the host) is used
                        by Datadog Agent to store information about processed log
                        files. If the Datadog Agent is restarted, it allows to start
                        tailing the log files from the right offset Default to `/var/lib/datadog-agent/logs`
                      type: string
                    useHttp:
                      description: Configure the Datadog Agent to send logs through 
                        HTTPS.
                      type: boolean
                  type: object
```

[Other configuration settings for HTTPS log forwarding](https://docs.datadoghq.com/agent/logs/?tab=httpcompressed#send-logs-over-https) can be configured as environment variables. Adding fields for them would be convenient, but not necessary to solve this use case.
