### ISSUE TITLE
Install Release Candidate 1.0.0-rc.6

### ISSUE THREAD

**Issue by Osazz** [DataDog/datadog-operator#689]
**Output of the info page (if this is a bug)**
```
{"level":"INFO","ts":"2023-01-18T16:47:17Z","logger":"setup","msg":"Version: v1.0.0-rc.6"}
{"level":"INFO","ts":"2023-01-18T16:47:17Z","logger":"setup","msg":"Build time: 2023-01-12/21:59:55"}
{"level":"INFO","ts":"2023-01-18T16:47:17Z","logger":"setup","msg":"Git Commit: 3172311206a0d105b6c4ceb410d6eb7f786ea1f7"}
{"level":"INFO","ts":"2023-01-18T16:47:17Z","logger":"setup","msg":"Go Version: go1.18.10"}
{"level":"INFO","ts":"2023-01-18T16:47:17Z","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
{"level":"INFO","ts":"2023-01-18T16:47:17Z","logger":"setup","msg":"Manager will be watching namespace","namespace":""}
{"level":"INFO","ts":"2023-01-18T16:47:18Z","logger":"klog","msg":"Waited for 1.040407427s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/install.istio.io/v1alpha1?timeout=32s\n"}
{"level":"INFO","ts":"2023-01-18T16:47:19Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8383"}
{"level":"INFO","ts":"2023-01-18T16:47:19Z","logger":"setup","msg":"starting manager"}
{"level":"INFO","ts":"2023-01-18T16:47:19Z","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8383"}
{"level":"INFO","ts":"2023-01-18T16:47:19Z","logger":"klog","msg":"attempting to acquire leader lease datadog-system/datadog-operator-lock...\n"}
{"level":"INFO","ts":"2023-01-18T16:47:19Z","msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"klog","msg":"successfully acquired lease datadog-system/datadog-operator-lock\n"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v2alpha1.DatadogAgent"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.Secret"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.ConfigMap"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.DaemonSet"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.Deployment"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.Role"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.RoleBinding"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.ServiceAccount"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1beta1.PodDisruptionBudget"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.NetworkPolicy"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.ClusterRole"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","source":"kind source: *v1.ClusterRoleBinding"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogagent","msg":"Starting Controller","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogmonitor","msg":"Starting EventSource","reconciler group":"datadoghq.com","reconciler kind":"DatadogMonitor","source":"kind source: *v1alpha1.DatadogMonitor"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"controller.datadogmonitor","msg":"Starting Controller","reconciler group":"datadoghq.com","reconciler kind":"DatadogMonitor"}
{"level":"INFO","ts":"2023-01-18T16:48:31Z","logger":"KubeAPIWarningLogger","msg":"policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget"}
{"level":"INFO","ts":"2023-01-18T16:48:32Z","logger":"DatadogMetricForwarders","msg":"New Datadog metrics forwarder registred","ID":"datadog-system/datadog"}
{"level":"INFO","ts":"2023-01-18T16:48:32Z","logger":"DatadogMetricForwarders","msg":"Starting Datadog metrics forwarder","CustomResource.Namespace":"datadog-system","CustomResource.Name":"datadog"}
{"level":"INFO","ts":"2023-01-18T16:48:32Z","logger":"DatadogMetricForwarders","msg":"Got Datadog Site","CustomResource.Namespace":"datadog-system","CustomResource.Name":"datadog","site":"https://api.datadoghq.com"}
{"level":"ERROR","ts":"2023-01-18T16:48:32Z","logger":"klog","msg":"Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\ngoroutine 549 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x1956720?, 0x2cd4bc0})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:74 +0x86\nk8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x73?})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:48 +0x75\npanic({0x1956720, 0x2cd4bc0})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).getCredentialsV2(0xc000f79730?, 0xc000f79600)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:582 +0x69\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).setupV2(0xc000396000)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:253 +0x238\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).connectToDatadogAPI(0xc000396000)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:295 +0x58\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x18, 0xc000100800})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:220 +0x1b\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1e7f130?, 0xc0006ca600?}, 0xc0007efdd0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:233 +0x57\nk8s.io/apimachinery/pkg/util/wait.poll({0x1e7f130, 0xc0006ca600}, 0x10?, 0xf4a905?, 0xc000eda810?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:580 +0x38\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x1e7f130, 0xc0006ca600}, 0x10?, 0xc000100800?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:545 +0x49\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc000396000?, 0xc000ead8c0?, 0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:536 +0x7c\ngithub.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).start(0xc000396000, 0x0?)\n\t/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:157 +0x10c\ncreated by github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*ForwardersManager).Register\n\t/workspace/pkg/controller/utils/datadog/forwarders_manager.go:66 +0x2a5\n"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e1069]

goroutine 549 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x73?})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1956720, 0x2cd4bc0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).getCredentialsV2(0xc000f79730?, 0xc000f79600)
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:582 +0x69
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).setupV2(0xc000396000)
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:253 +0x238
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).connectToDatadogAPI(0xc000396000)
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:295 +0x58
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x18, 0xc000100800})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:220 +0x1b
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1e7f130?, 0xc0006ca600?}, 0xc0007efdd0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:233 +0x57
k8s.io/apimachinery/pkg/util/wait.poll({0x1e7f130, 0xc0006ca600}, 0x10?, 0xf4a905?, 0xc000eda810?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:580 +0x38
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext({0x1e7f130, 0xc0006ca600}, 0x10?, 0xc000100800?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:545 +0x49
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0xc000396000?, 0xc000ead8c0?, 0x0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:536 +0x7c
github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*metricsForwarder).start(0xc000396000, 0x0?)
	/workspace/pkg/controller/utils/datadog/metrics_forwarder.go:157 +0x10c
created by github.com/DataDog/datadog-operator/pkg/controller/utils/datadog.(*ForwardersManager).Register
	/workspace/pkg/controller/utils/datadog/forwarders_manager.go:66 +0x2a5

```

**Describe what happened:**
Trying to install 1.0.0-rc.6 because we have a bug that is fixed in it and wants to upgrade asap. It currently in 
CrashLoopBackOff because of the error in the log above. I know this is not release yet but I am hoping to get an insight into how I can install this. 

**Describe what you expected:**
Operator should not fail 

**Steps to reproduce the issue:**
- helm install datadog-operator datadog/datadog-operator --set image.tag=1.0.0-rc.5
- kubectl -n argocd create -f datadog-agent.yaml

`datadog-agent.yaml` looks like this 

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  agent:
    image:
      name: "gcr.io/datadoghq/agent:7.41.1"
    rbac:
      create: true
    config:
      tolerations:
        - operator: Exists
    env:
      ...
  clusterAgent:
    image:
      name: "gcr.io/datadoghq/cluster-agent:7.41.1"
    rbac:
      create: true
    config:
      clusterChecksEnabled: false
      collectEvents: true

```
**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by levan-m** [comment]
Hello, thanks for reporting the issue! I was able to reproduce this locally and can confirm this is a bug. I'll add it to our backlog - this a GA blocker and will be handled with priority.

I don't have any workaround at the moment unfortunately.

**Comment by GenPage** [comment]
I am also seeing this on 1.0.0-rc.7 just to add additional logic

**Comment by levan-m** [comment]
Hello, I did some more investigation and root cause of the above failure is incompatibility between `v1alpha1` and `v2alpha1` schemas. Problem isn't necessarily in the code though. 

`helm install datadog-operator datadog/datadog-operator --set image.tag=1.0.0-rc.5` installs image which out of the box manages `v2alpha1`, while underlying stored version of CRD is `v1alpha1`. Above command configures conversion strategy `None`, so `v1alpha1` is served using `v2alpha1` schema leading to incorrect pointer dereference.

To resolve the issue one could make `v2alpha1` the stored version with:
`helm install datadog-operator datadog/datadog-operator --set image.tag=1.0.0-rc.5 --set datadog-crds.migration.datadogAgents.version=v2alpha1`
and use `v2alpha1` manifest to setup the agents. This setup still has `v1alpha1` as served version, however doesn't have the conversion webhook so `v1alpha1` manifest can't be used. Webhook conversion setup isn't yet supported by current Operator chart.

**Comment by GenPage** [comment]
@levan-m Thanks digging into this issue. So the options are either:
- Keep using an operator version prior to the 1.0 pre-release candidates
- Update our Agent schema to v2alpha1

Are there any good migration docs on converting the schema spec? I noticed that it seems most of the configuration shifted into the `override` key in v2alpha1. is it just a lift and shift or more involved than that?

**Comment by Osazz** [comment]
@levan-m  Thanks for digging and your suggestion works. 


```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    clusterName: <name of cluster>
    kubelet:
      tlsVerify: false
  features:
    apm:
      enabled: true
      unixDomainSocketConfig:
        enabled: false
    liveProcessCollection:
      enabled: true
    otlp:
      receiver:
        protocols:
          http:
            enabled: true
          grpc:
            enabled: true
  override:
    nodeAgent:
      image:
        name: agent
        tag: 7.42.0
      tolerations:
        - operator: Exists
      securityContext:
        runAsUser: 101
      volumes:
        - emptyDir: {}
          name: datadog-tmp
      volumeMounts:
        - mountPath: /tmp
          name: datadog-tmp
    clusterAgent:
      image:
        name: cluster-agent
        tag: 7.42.0
      env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
```

Sample of Agent that work for me is this and closing this

**Comment by jsjupiter** [comment]
@Osazz  where can I find a reference for this apiversion, I've set up my operator to 1.0.0-rc.7  and created my agent manifest using [this](https://github.com/DataDog/datadog-operator/blob/d94287ebf8817829bc408fe9ab94a91081b988b9/docs/configuration.v2alpha1.md#override): 

Here is my manifest:

```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: <>
    criSocketPath: <>
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: <>
      appSecret:
        secretName: datadog-secret
        keyName: <>
  features:
    usm:
      enabled: true
    apm:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    liveProcessCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    clusterChecks:
      enabled: true
      useClusterChecksRunners: true 
    # externalMetricsServer:
    #   enabled: true
    logCollection: 
      enabled: true
      containerCollectAll: true 
      containerCollectUsingFiles: true
    admissionController:
      enabled: true
      mutateUnlabelled: false
  override:
    nodeAgent:
      image:
        name: "gcr.io/datadoghq/agent:latest"
      tolerations:
        - operator: Exists
    clusterAgent:
      createRbac: true
      image:
        name: "gcr.io/datadoghq/cluster-agent:latest"
    clusterChecksRunner:
      image:
        name: "gcr.io/datadoghq/agent:latest"
  ```
