### ISSUE TITLE
Feature Request: Support composite monitors

### ISSUE THREAD

**Issue by jonnylangefeld** [DataDog/datadog-operator#699]
When creating a composite monitor like
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: my-monitor
spec:
  ...
  type: composite
```

I get this message in the status:
```
status:
  conditions:
  - lastTransitionTime: "2023-01-31T09:41:06Z"
    lastUpdateTime: "2023-01-31T09:41:06Z"
    message: monitor type composite not supported
    status: "True"
    type: Error
```

We are currently using composite monitors created via terraform but want to switch to the operator. Can we enable composite resources?
