### ISSUE TITLE
Unified Service Tagging Double env Environment

### ISSUE THREAD

**Issue by engesin** [DataDog/datadog-operator#702]
**Describe what happened:**
Hi all,

I want to set `env` environment variable by setting `DD_ENV` but what I see in Dashboard is duplicated `evn` tagging. I assume the first one comes from [Unified Service Tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes).

How can I override that tag? 

```
spec:
  clusterAgent:
    config:
      env:
      - name: DD_ENV
        value: labsstg-dr
      - name: DD_ORCHESTRATOR_EXPLORER_EXTRA_TAGS
        value: DD_ENV:labsstg-dr env:labsstg-dr
  agent:
    env:
    - name: DD_ENV
      value: labsstg-dr
    - name: DD_ORCHESTRATOR_EXPLORER_EXTRA_TAGS
      value: DD_ENV:labsstg-dr env:labsstg-dr
    - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
      value: 'true'
```

![image](https://user-images.githubusercontent.com/5075124/216012354-60255424-f46b-4c7f-a804-d6f540f5dfb1.png)

**Describe what you expected:**
I want to see only `env:labsstg-dr`

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc): AWS
