### ISSUE TITLE
Feature request:  CRD for Service Definition

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#761]
The Datadog integrations with Kubernetes already provide a series of CRDs for metrics and monitors as well as the CRDs provided here for the operator.  An additional useful resource would be a Service Definition.  

It could behave much the same way as creating a Service Definition in Terraform (see here: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/service_definition_yaml) but the yaml would be validated for formatting and stored in the kubernetes cluster alongside the app it describes, while the operator keeps it up to date in the DataDog account.

**Comment by demolitionmode** [comment]
> It could behave much the same way as creating a Service Definition in Terraform

Do you think something like the following would be a reasonable manifest?

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogServiceDefinition
metadata:
  name: foo
spec:
  serviceDefinition: |
    schema-version: v2.2
    dd-service: shopping-cart
    team: e-commerce-team
    ...
```
