### ISSUE TITLE
Service ports do not change for datadog-agent if changed default HostPort for dogstatsd

### ISSUE THREAD

**Issue by danil-ivanoff** [DataDog/datadog-operator#820]
**Describe what happened:**
Service ports do not change for datadog-agent if changed default HostPort for dogstatsd
`datadog-agent                           ClusterIP   10.233.35.185   <none>        8126/TCP,8125/UDP   20m`
```
features:
    dogstatsd:
      hostPortConfig:
        enabled: true
        hostPort: 8127
```

**Describe what you expected:**
Service ports are changed

**Steps to reproduce the issue:**
```
features:
    dogstatsd:
      hostPortConfig:
        enabled: true
        hostPort: 8127
```

**Additional environment details (Operating System, Cloud provider, etc):**
Problem is [here](https://github.com/DataDog/datadog-operator/blob/855210430403f4b8151cef75fea9a593e39eb580/controllers/datadogagent/service.go#L438) 
DefaultDogstatsdPort using, not a HostPort. But in same time - APM using right HostPort [here](https://github.com/DataDog/datadog-operator/blob/855210430403f4b8151cef75fea9a593e39eb580/controllers/datadogagent/service.go#L451)
```
Ports: []corev1.ServicePort{
				{
					Protocol:   corev1.ProtocolUDP,
					TargetPort: intstr.FromInt(apicommon.DefaultDogstatsdPort),
					Port:       apicommon.DefaultDogstatsdPort,
					Name:       apicommon.DefaultDogstatsdPortName,
				},
			},
```
