### ISSUE TITLE
DatadogMonitor not controlled outside datadog-operator namespace

### ISSUE THREAD

**Issue by ademsayin-essentx** [DataDog/datadog-operator#832]
**Describe what happened:**
I tried to apply a DatadogMonitor in a different namespace than datadog-operator is deployed.
The DatadogMonitor resource was not deployed on Datadog through datadog-operator.

```
NAME           ID    MONITOR STATE   LAST TRANSITION   LAST SYNC   SYNC STATUS   AGE
test-monitor                                                                     10s
```

Datadog-operator log does not show any monitor deployed.

Tried the same monitor spec in the same namespace as datadog-operator is deployed and it was picked up immediately.

```
NAME           ID         MONITOR STATE   LAST TRANSITION        LAST SYNC              SYNC STATUS   AGE
test-monitor   11934251   No Data         2023-07-04T13:08:08Z   2023-07-04T13:08:08Z   OK            4s
```

**Describe what you expected:**
DatadogMonitor in a different namespace than datadog-operator is running in will be controlled and deployed to Datadog.

**Steps to reproduce the issue:**

- Install latest version 1.0.3
- enable monitor support in values.yaml: `datadogMonitor.enabled: true`

DatadogMonitor example used:
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: test-monitor
spec:
  message: test-monitor
  name: test-monitor
  query: "avg(last_10m):avg:system.disk.in_use{*} by {host} > 0.5"
  type: metric alert
```

**Additional environment details (Operating System, Cloud provider, etc):**
EKS - Kubernetes 1.24

Should datadog-operator control DatadogMonitor resources in other namespaces? I don't know if this is a bug or a feature request.

Thanks
