### ISSUE TITLE
Using the admission controller breaks topologySpreadConstraint

### ISSUE THREAD

**Issue by joshuabaird** [DataDog/datadog-operator#874]
**Describe what happened:**
I have a _Deployment_ that looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app
    tags.datadoghq.com/env: staging
    tags.datadoghq.com/service: app
    tags.datadoghq.com/version: latest    
  name: web
  namespace: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app
   template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: core-api
        admission.datadoghq.com/enabled: "true"
    spec:
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: app
        maxSkew: 1
        minDomains: 3
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
```

The _topologySpreadConstraint_ is targeting pods with the `app.kubernetes.io/name=app` label.  With the admission controller enabled (via the label above), the _topologySpreadConstraint_  does not work -- it seems as if the mutating web hook is mangling the other labels on the pods or something.

If I remove the `admission.datadoghq.com/enabled=true` label from the _Deployment_ -- the _topologySpreadConstraint_  works as expected/specified.

**Describe what you expected:**
The _topologySpreadConstraint_  should work.

**Steps to reproduce the issue:**
Create a _Deployment_ like the example above.  Observe the _topologySpreadConstraint_  not working correctly (eg, not selecting the proper pods as configured to do so).

**Additional environment details (Operating System, Cloud provider, etc):**
AWS/EKS 1.27/Datadog Operator 1.0.7.
