### ISSUE TITLE
Loading environment variables using envFrom 

### ISSUE THREAD

**Issue by Ekman** [DataDog/datadog-operator#896]
This is potentially a feature request.

Is it possible to use the `envFrom`, or something similar that produces the same results?

```yaml
override:
  nodeAgent:
    envFrom:
      - secretRef:
          name: my-secret-secret
```
