### ISSUE TITLE
Add ability to select the secret key for apiKeyExistingSecret and appKeyExistingSecret

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#95]
Currently, to pass the API key or the APP key as secret, the only way to do it is to pass the name of the secret and it expects the api key to be in the `api_key` key of the secret and the app key to be in the `app_key` key of the secret. 

I think we shouldn't assume the key name.

My suggestion would be to have something like:

```
apiKeyExistingSecret:
  secretName: string
  keyName: string
```

**Comment by clamoriniere** [comment]
Hi @arapulido,

Your suggestion makes sense.

The current implementation comes from the ["stable/datadog" helm chart](https://github.com/helm/charts/blob/master/stable/datadog/values.yaml#L28) that also assume the users are using the `api_key` and `app_key`.

To apply your suggestion it requires to make a breaking change in the `DatadogAgent` CRD definition. So It means a new CRD version: v1alpha2 or v1beta1. 
Else it means we need to add another parameter, but it will add some complexity.

WDYT?

**Comment by arapulido** [comment]
I haven't used the helm chart a lot, so I didn't know it was there as well. In the helm chart is less common to use that field, though, as the instructions suggest to pass the api key as parameter:
```
helm install <RELEASE_NAME> -f values.yaml  --set datadog.apiKey=<DATADOG_API_KEY> stable/datadog --set targetSystem=<TARGET_SYSTEM>
```
In this case it is more likely to be use the apiKeyExistingSecret, as you need to store it in your git configuration repo, without the ability to pass the api key as parameter when deploying. 

I don't think this type of magic numbers (or in this case, magic key) do any good (I think we should change it in the helm chart as well, but neither of those are my decision to make).

As for the new CRD object version vs new parameter option, I would leave that to your discretion :)

Thanks for taking the suggestion into account!

**Comment by L3n41c** [comment]
In order to not have backward compatibility issue, I created new parameters instead of changing the expected content type of the existing parameters.

So, now, instead of:
```yaml
credentials:
  apiKeyExistingSecret: secretapi
  appKeyExistingSecret: secretapp
```
it’s possible to put:
```yaml
credentials:
  apiSecret:
    secretName: secretapi
    keyName: api_key  # This fields is optional as it defaults to "api_key" in "apiSecret" context
  appSecret:
    secretName: secretapp
    keyName: app_key  # This field is optional as it defaults to "app_key" in "appSecret" context
```

For backward compatibility reasons, the `apiKeyExistingSecret` and `appKeyExistingSecret` parameters are still present but should be considered as deprecated.
