### ISSUE TITLE
If appKeyExistingSecret is specified, then the token secret fails to create

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#96]
**Output of the info page (if this is a bug)**
What is the info page??

**Describe what happened:**

I have setup my app key in a secret that I have created previously, called `secretapp`. I set up my cluster token in plain text under the `token` field. This is a snippet of my agent spec:

```
spec:
  credentials:
    apiKeyExistingSecret: secretapi
    appKeyExistingSecret: secretapp
    token: "<ThirtyX2XcharactersXlongXtoken>"
```

The cluster-agent fails to run, because it expects that the `secretapp` key to have a token key. 

```
  Warning  Failed     2s (x3 over 16s)  kubelet, kind-worker2  Error: couldn't find key token in Secret datadog/secretapp
```
**Describe what you expected:**

If the `token` key is not there, edit the secret and add the `token` key using the string passed in the `token` spec.

**Steps to reproduce the issue:**

Create an agent and cluster agent with the appkey passed as secret and try to pass a token:

```
spec:
  credentials:
    apiKeyExistingSecret: secretapi
    appKeyExistingSecret: secretapp
    token: "<ThirtyX2XcharactersXlongXtoken>"
```

**Comment by L3n41c** [comment]
Hello @arapulido !

Which version of the Datadog operator did you try ?

I don’t reproduce this issue with the `master` version of the operator.
With this in the CR:
```
  credentials:
    apiKeyExistingSecret: secretapi
    appKeyExistingSecret: secretapp
    token: "<ThirtyX2XcharactersXlongXtoken>"
```
my cluster agent is properly starting and has this in his description:
```
kubectl describe pod/datadog-agent-cluster-agent-7b7f46f6-9tk4x
[…]
    Environment:
      DD_CLUSTER_AGENT_AUTH_TOKEN:               <set to the key 'token' in secret 'datadog-agent'>  Optional: false
      DD_API_KEY:                                <set to the key 'api_key' in secret 'secretapi'>  Optional: false
      DD_APP_KEY:                                <set to the key 'app_key' in secret 'secretapp'>  Optional: false
[…]
```

The symptoms you are describing (having the operator looking for the `token` key in the `app` secret were most probably coming from lines 979 and 980 in https://github.com/DataDog/datadog-operator/pull/77/files#diff-774712c4d6c0043f8644114d90319ebb, but it is now fixed.
```go
	authTokenValue.SecretKeyRef.Name = utils.GetAppKeySecretName(dda)
	authTokenValue.SecretKeyRef.Key = "token"
```

**Comment by arapulido** [comment]
The first time I tried this I think I was using 0.1.3 I believe, as the Getting Started was pointing to that one: https://github.com/DataDog/datadog-operator/pull/98

I think I opened this one when I was using 0.1.3 so you might be right.

**Comment by jessecollier** [comment]
Posting an update, since its been awhile.

A couple of findings:
1. If token is missing, it will reference a secret name for the Auth token variable matching that of the `kind: DatadogAgent`'s Name 
2. If `apiKeyExistingSecret` OR the new `apiSecret` is configured, then a token will not be generated (since the operator does not own the secret)

The logic should still create a secret for the token if it is to be dynamically generated, even if there is a different secret used for the api and app keys.

Reference:
If you are seeing this error when you have specified your OWN secret for api/app keys
```
Error: secret "datadog-operator-datadog-agent-with-operator" not found
```

It is because the cluster-agent is configured with an [env var secret reference](https://github.com/DataDog/datadog-operator/blob/81620bc9aa8fc3692f1f0d550a37104d3137f2ae/pkg/controller/datadogagent/utils.go#L1371-L1381). 
```
    - name: DD_CLUSTER_AGENT_AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: datadog-operator-datadog-agent-with-operator
```
The name is [derived](https://github.com/DataDog/datadog-operator/blob/81620bc9aa8fc3692f1f0d550a37104d3137f2ae/pkg/controller/datadogagent/utils.go#L43-L45) from the `kind: DatadogAgent`'s name.

However, the [token generation](https://github.com/DataDog/datadog-operator/blob/cb2eac81f10899257f85e2406ccb08c862d1fdd2/pkg/controller/datadogagent/secret.go#L132) is done when the token is not provided. But when it goes to "save" this token, it does not because the [Api Secret](https://github.com/DataDog/datadog-operator/blob/cb2eac81f10899257f85e2406ccb08c862d1fdd2/pkg/controller/datadogagent/secret.go#L135) is [not owned by the operator.](https://github.com/DataDog/datadog-operator/blob/cb2eac81f10899257f85e2406ccb08c862d1fdd2/pkg/controller/datadogagent/secret.go#L72-L74)
