### ISSUE TITLE
If cspm is enabled, `the server could not find the requested resource` continues

### ISSUE THREAD

**Issue by inobu** [DataDog/datadog-operator#975]
**Output of the info page (if this is a bug)**
```
RBAC: allowed by ClusterRoleBinding "default-datadog-cspm-cluster-agent" of ClusterRole "default-datadog-cspm-cluster-agent" to ServiceAccount "datadog-cluster-agent/default"
```

**Describe what happened:**
If cspm is enabled, `the server could not find the requested resource` continues.
Therefore, at least in GKE, control plane upgrades are not automatically performed.

**Describe what you expected:**
There will be no errors

**Steps to reproduce the issue:**
```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  features:
    cspm:
      enabled: true
```

**Additional environment details (Operating System, Cloud provider, etc):**
GKE 1.25
